In [1]:
import pandas as pd 
df = pd.read_csv('../data/processed/modelB_dataset.csv')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   dyad                      1440 non-null   str    
 1   year                      1440 non-null   int64  
 2   regime_diff               1440 non-null   float64
 3   MonthYear                 1440 non-null   int64  
 4   event_count               1440 non-null   float64
 5   goldstein_std             1440 non-null   float64
 6   goldstein_min             1440 non-null   float64
 7   num_mentions_sum          1440 non-null   float64
 8   num_articles_sum          1440 non-null   float64
 9   num_sources_sum           1440 non-null   float64
 10  high_conflict_count       1440 non-null   float64
 11  low_conflict_count        1440 non-null   float64
 12  quad4_count               1440 non-null   float64
 13  high_conflict_pct         1440 non-null   float64
 14  low_conflict_pct   

In [2]:
# define data
X = df.loc[:, ['regime_diff','event_count_lag1', 'goldstein_std_lag1', 'goldstein_min_lag1', 'num_mentions_sum_lag1',
               'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1',
               'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']]
y = df['monthly_label']

# 先按時間一刀切
train_mask = df['MonthYear'] < 202301
test_mask =  df['MonthYear'] >= 202301
X_train, X_test = X[train_mask], X[test_mask]
y_train, y_test = y[train_mask], y[test_mask]

In [6]:
# lgb model
from lightgbm import LGBMClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn import set_config
set_config(display='text')
lgb_params = {
    'objective': 'multiclass',
    'boosting_type': 'gbdt',
    'learning_rate': 0.05,       
    'num_leaves': 7,             
    'max_depth': 3,               
    'min_child_samples': 20,      
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'reg_alpha': 0.1,             
    'reg_lambda': 0.1,            
    'random_state': 42,
}
mod1 = LGBMClassifier(**lgb_params)
mod1.fit(X_train, y_train,
         sample_weight=compute_sample_weight('balanced',  y_train))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002354 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2886
[LightGBM] [Info] Number of data points in the train set: 1044, number of used features: 13
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Info] Start training from score -1.098612
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

LGBMClassifier(colsample_bytree=0.8, learning_rate=0.05, max_depth=3,
               num_leaves=7, objective='multiclass', random_state=42,
               reg_alpha=0.1, reg_lambda=0.1, subsample=0.8)

In [9]:
from sklearn.metrics import classification_report, roc_auc_score

predict_train = mod1.predict(X_train)
predict_test = mod1.predict(X_test)
report_train = classification_report(y_train, predict_train)
report_test = classification_report(y_test, predict_test)
print(f'train: {report_train}')
print(f'test: {report_test}')
# auc
y_pred_proba = mod1.predict_proba(X_test)  
auc_macro = roc_auc_score(y_test, y_pred_proba, multi_class='ovr', average='macro')
print(f'Macro AUC: {auc_macro:.3f}')

#　個別
from sklearn.preprocessing import label_binarize
classes = mod1.classes_
y_test_binarized = label_binarize(y_test, classes=classes)
for i, cls in enumerate(classes):
    auc = roc_auc_score(y_test_binarized[:, i], y_pred_proba[:, i])
    print(f'{cls} AUC: {auc:.3f}')


train:                precision    recall  f1-score   support

  Cooperation       0.96      0.87      0.91       777
High_Conflict       0.71      0.95      0.81        95
 Low_Conflict       0.64      0.81      0.71       172

     accuracy                           0.86      1044
    macro avg       0.77      0.87      0.81      1044
 weighted avg       0.89      0.86      0.87      1044

test:                precision    recall  f1-score   support

  Cooperation       0.93      0.92      0.93       244
High_Conflict       0.56      0.61      0.59        44
 Low_Conflict       0.72      0.72      0.72       108

     accuracy                           0.83       396
    macro avg       0.74      0.75      0.74       396
 weighted avg       0.83      0.83      0.83       396

Macro AUC: 0.894
Cooperation AUC: 0.944
High_Conflict AUC: 0.888
Low_Conflict AUC: 0.850


In [11]:
import pandas as pd

importance_df = pd.DataFrame({
    'feature': mod1.feature_name_,
    'gain': mod1.booster_.feature_importance(importance_type='gain')
}).sort_values('gain', ascending=False)

print(importance_df)

                     feature         gain
0                regime_diff  5848.255845
11     low_conflict_pct_lag1  4217.782484
10    high_conflict_pct_lag1  2458.188159
2         goldstein_std_lag1  1110.509124
12            quad4_pct_lag1   815.677218
8    low_conflict_count_lag1   571.416836
7   high_conflict_count_lag1   297.733862
4      num_mentions_sum_lag1   266.366418
9           quad4_count_lag1   237.564881
6       num_sources_sum_lag1   215.309913
1           event_count_lag1   198.854423
5      num_articles_sum_lag1   138.198260
3         goldstein_min_lag1     2.819430


In [20]:
from sklearn.model_selection import LeaveOneGroupOut
from lightgbm import LGBMClassifier
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.metrics import recall_score
import numpy as np

logo = LeaveOneGroupOut()
groups = df['dyad']

lgb_params = {
    'objective': 'multiclass',
    'boosting_type': 'gbdt',
    'learning_rate': 0.05,
    'num_leaves': 7,
    'max_depth': 3,
    'min_child_samples': 20,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'reg_alpha': 0.1,
    'reg_lambda': 0.1,
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1,
}

results = []

for train_idx, test_idx in logo.split(X, y, groups):
    left_out_dyad = groups.iloc[test_idx].unique()[0]
    
    X_train_fold, X_test_fold = X.iloc[train_idx], X.iloc[test_idx]
    y_train_fold, y_test_fold = y.iloc[train_idx], y.iloc[test_idx]
    
    model = LGBMClassifier(**lgb_params)
    model.fit(X_train_fold, y_train_fold, sample_weight=compute_sample_weight('balanced', y_train_fold))
    
    y_pred_fold = model.predict(X_test_fold)
    
    recall_macro = recall_score(y_test_fold, y_pred_fold, average='macro', zero_division=0)
    
    results.append({'left_out_dyad': left_out_dyad, 'recall_macro': recall_macro})
    print(f'{left_out_dyad}: recall_macro = {recall_macro:.3f}')

results_df = pd.DataFrame(results)
print(results_df)
print(f'平均 recall_macro: {results_df["recall_macro"].mean():.3f}')

CHN-JPN: recall_macro = 0.461
CHN-KOR: recall_macro = 0.310
CHN-PHL: recall_macro = 0.498
CHN-PRK: recall_macro = 0.333
CHN-TWN: recall_macro = 0.695
CHN-VNM: recall_macro = 0.642
JPN-KOR: recall_macro = 0.318
JPN-PRK: recall_macro = 0.459
JPN-TWN: recall_macro = 0.496
KOR-PRK: recall_macro = 0.541
KOR-TWN: recall_macro = 0.311
   left_out_dyad  recall_macro
0        CHN-JPN      0.460979
1        CHN-KOR      0.310256
2        CHN-PHL      0.498176
3        CHN-PRK      0.333333
4        CHN-TWN      0.694677
5        CHN-VNM      0.642077
6        JPN-KOR      0.317829
7        JPN-PRK      0.459259
8        JPN-TWN      0.496124
9        KOR-PRK      0.541453
10       KOR-TWN      0.311475
平均 recall_macro: 0.461


In [22]:
lag_cols = ['event_count_lag1', 'goldstein_std_lag1', 'goldstein_min_lag1', 'num_mentions_sum_lag1',
           'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1',
           'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']
X_no_regime = df[lag_cols]  

results_no_regime = []

for train_idx, test_idx in logo.split(X_no_regime, y, groups):
    left_out_dyad = groups.iloc[test_idx].unique()[0]
    
    X_train_fold, X_test_fold = X_no_regime.iloc[train_idx], X_no_regime.iloc[test_idx]
    y_train_fold, y_test_fold = y.iloc[train_idx], y.iloc[test_idx]
    
    model = LGBMClassifier(**lgb_params)
    model.fit(X_train_fold, y_train_fold, sample_weight=compute_sample_weight('balanced', y_train_fold))
    
    y_pred_fold = model.predict(X_test_fold)
    recall_macro = recall_score(y_test_fold, y_pred_fold, average='macro', zero_division=0)
    
    results_no_regime.append({'left_out_dyad': left_out_dyad, 'recall_macro': recall_macro})
    print(f'{left_out_dyad}: recall_macro = {recall_macro:.3f}')

results_no_regime_df = pd.DataFrame(results_no_regime)
print(f'平均 recall_macro（無 regime_diff）: {results_no_regime_df["recall_macro"].mean():.3f}')

CHN-JPN: recall_macro = 0.472
CHN-KOR: recall_macro = 0.651
CHN-PHL: recall_macro = 0.471
CHN-PRK: recall_macro = 0.470
CHN-TWN: recall_macro = 0.467
CHN-VNM: recall_macro = 0.353
JPN-KOR: recall_macro = 0.310
JPN-PRK: recall_macro = 0.509
JPN-TWN: recall_macro = 0.326
KOR-PRK: recall_macro = 0.540
KOR-TWN: recall_macro = 0.298
平均 recall_macro（無 regime_diff）: 0.442


In [26]:
# 排除 goldstein_min_lag1
features = ['regime_diff', 'event_count_lag1', 'goldstein_std_lag1', 'goldstein_min_lag1', 'num_mentions_sum_lag1',
           'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1',
           'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']
lag_cols_trimmed = [col for col in features if col != 'goldstein_min_lag1']
print(lag_cols_trimmed)

X_trimmed = df[lag_cols_trimmed]
y = df['monthly_label']

X_train_trimmed = X_trimmed[train_mask]
X_test_trimmed = X_trimmed[test_mask]

mod_trimmed = LGBMClassifier(**lgb_params)
mod_trimmed.fit(X_train_trimmed, y_train, sample_weight=compute_sample_weight('balanced', y_train))

pred_train_trimmed = mod_trimmed.predict(X_train_trimmed)
pred_test_trimmed = mod_trimmed.predict(X_test_trimmed)

print('train:', classification_report(y_train, pred_train_trimmed))
print('test:', classification_report(y_test, pred_test_trimmed))


['regime_diff', 'event_count_lag1', 'goldstein_std_lag1', 'num_mentions_sum_lag1', 'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1', 'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']
train:                precision    recall  f1-score   support

  Cooperation       0.96      0.86      0.91       777
High_Conflict       0.69      0.95      0.80        95
 Low_Conflict       0.64      0.81      0.71       172

     accuracy                           0.86      1044
    macro avg       0.77      0.87      0.81      1044
 weighted avg       0.89      0.86      0.87      1044

test:                precision    recall  f1-score   support

  Cooperation       0.92      0.91      0.92       244
High_Conflict       0.55      0.61      0.58        44
 Low_Conflict       0.72      0.70      0.71       108

     accuracy                           0.82       396
    macro avg       0.73      0.74      0.74  

In [ ]:
# 排除 goldstein_min_lag1
features = ['regime_diff', 'event_count_lag1', 'goldstein_std_lag1', 'goldstein_min_lag1', 'num_mentions_sum_lag1',
           'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1',
           'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']
lag_cols_trimmed = [col for col in features if col != 'goldstein_min_lag1']
print(lag_cols_trimmed)

X_trimmed = df[lag_cols_trimmed]
y = df['monthly_label']

X_train_trimmed = X_trimmed[train_mask]
X_test_trimmed = X_trimmed[test_mask]

mod_trimmed = LGBMClassifier(**lgb_params)
mod_trimmed.fit(X_train_trimmed, y_train, sample_weight=compute_sample_weight('balanced', y_train))

pred_train_trimmed = mod_trimmed.predict(X_train_trimmed)
pred_test_trimmed = mod_trimmed.predict(X_test_trimmed)

print('train:', classification_report(y_train, pred_train_trimmed))
print('test:', classification_report(y_test, pred_test_trimmed))


['regime_diff', 'event_count_lag1', 'goldstein_std_lag1', 'num_mentions_sum_lag1', 'num_articles_sum_lag1', 'num_sources_sum_lag1', 'high_conflict_count_lag1', 'low_conflict_count_lag1', 'quad4_count_lag1', 'high_conflict_pct_lag1', 'low_conflict_pct_lag1', 'quad4_pct_lag1']
train:                precision    recall  f1-score   support

  Cooperation       0.96      0.86      0.91       777
High_Conflict       0.69      0.95      0.80        95
 Low_Conflict       0.64      0.81      0.71       172

     accuracy                           0.86      1044
    macro avg       0.77      0.87      0.81      1044
 weighted avg       0.89      0.86      0.87      1044

test:                precision    recall  f1-score   support

  Cooperation       0.92      0.91      0.92       244
High_Conflict       0.55      0.61      0.58        44
 Low_Conflict       0.72      0.70      0.71       108

     accuracy                           0.82       396
    macro avg       0.73      0.74      0.74  

### 模型 B 實驗記錄：regime_diff（政體差異）

- 資料：V-Dem v2x_libdem，取絕對差，年度資料不用lag
- 結果：時間切分驗證下表現變差（HC recall 0.75→0.61），但 LODO 驗證下反而略好（0.461 vs 0.442）
- AUC（模型B）：Macro 0.894 / Cooperation 0.944 / High_Conflict 0.888 / Low_Conflict 0.850
  → 比模型A（Macro 0.917 / HC 0.935）略低，但排序能力仍算穩定
- Gain 顯示 regime_diff 排第一，遠高於其他特徵，懷疑是「認出dyad身份」的捷徑
- 排除 goldstein_min_lag1（gain幾乎0）測試，表現沒變，排除是其他特徵拖累的可能性
- 結論：證據不一致，樣本量（11組dyad）可能是根本限制，先不採用，留待未來擴充dyad後再評估

**目前模型只適用於已知的11組dyad，套用到全新dyad前要重新訓練，不能直接套用**

**因最終方案傾向輸出機率而非強制分類，AUC（排序能力）比recall/precision更該被優先參考**

In [28]:
# Optuna
import optuna
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import recall_score, classification_report
from lightgbm import LGBMClassifier
from sklearn.utils.class_weight import compute_sample_weight



def objective(trial):
    params = {
        'objective': 'multiclass',
        'boosting_type': 'gbdt',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 4, 31),
        'max_depth': trial.suggest_int('max_depth', 2, 8),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 50),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1,
    }

    tscv = TimeSeriesSplit(n_splits=5)
    scores = []

    for train_idx, val_idx in tscv.split(X_train):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        model = LGBMClassifier(**params)
        model.fit(X_tr, y_tr, sample_weight=compute_sample_weight('balanced', y_tr))

        y_pred = model.predict(X_val)
        score = recall_score(y_val, y_pred, average='macro', zero_division=0)
        scores.append(score)

    return np.mean(scores)


# ---- 執行搜尋 ----
study = optuna.create_study(direction='maximize', study_name='model_a_tuning')
study.optimize(objective, n_trials=100, show_progress_bar=True)

print('最佳參數:', study.best_params)
print('最佳 CV recall_macro:', study.best_value)

# ---- 用最佳參數，在完整訓練集上重新訓練，並在測試集上驗證 ----
print('\n=== 開始訓練最終模型 ===')
best_params = study.best_params.copy()
best_params.update({
    'objective': 'multiclass',
    'boosting_type': 'gbdt',
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1,
})

final_model = LGBMClassifier(**best_params)
final_model.fit(X_train, y_train, sample_weight=compute_sample_weight('balanced', y_train))

pred_train = final_model.predict(X_train)
pred_test = final_model.predict(X_test)

print('\n=== 調參後最終模型 ===')
print('train:', classification_report(y_train, pred_train))
print('test:', classification_report(y_test, pred_test))



[I 2026-08-17 17:52:01,234] A new study created in memory with name: model_a_tuning
Best trial: 0. Best value: 0.525608:   1%|          | 1/100 [00:02<04:19,  2.62s/it]

[I 2026-08-17 17:52:07,147] Trial 0 finished with value: 0.5256076069650056 and parameters: {'learning_rate': 0.06972428125228906, 'num_leaves': 15, 'max_depth': 5, 'min_child_samples': 14, 'subsample': 0.5888060145272878, 'colsample_bytree': 0.6714375521401117, 'reg_alpha': 0.6890602918807734, 'reg_lambda': 0.46206572623385156, 'n_estimators': 60}. Best is trial 0 with value: 0.5256076069650056.


Best trial: 1. Best value: 0.529412:   2%|▏         | 2/100 [00:03<02:31,  1.55s/it]

[I 2026-08-17 17:52:07,947] Trial 1 finished with value: 0.5294116419345001 and parameters: {'learning_rate': 0.045952845033122365, 'num_leaves': 29, 'max_depth': 2, 'min_child_samples': 31, 'subsample': 0.6809810938432432, 'colsample_bytree': 0.8620046016796271, 'reg_alpha': 0.6410592196873691, 'reg_lambda': 0.7419221105027765, 'n_estimators': 211}. Best is trial 1 with value: 0.5294116419345001.


Best trial: 2. Best value: 0.631338:   3%|▎         | 3/100 [00:04<01:51,  1.15s/it]

[I 2026-08-17 17:52:08,636] Trial 2 finished with value: 0.6313377828831057 and parameters: {'learning_rate': 0.011743030287962409, 'num_leaves': 31, 'max_depth': 8, 'min_child_samples': 30, 'subsample': 0.8614148545842597, 'colsample_bytree': 0.7306552938307926, 'reg_alpha': 0.9757353374097459, 'reg_lambda': 0.15956295778071417, 'n_estimators': 63}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   4%|▍         | 4/100 [00:05<01:44,  1.09s/it]

[I 2026-08-17 17:52:09,618] Trial 3 finished with value: 0.5198672533613714 and parameters: {'learning_rate': 0.03614130938815774, 'num_leaves': 16, 'max_depth': 8, 'min_child_samples': 19, 'subsample': 0.598971603397159, 'colsample_bytree': 0.5597284721941899, 'reg_alpha': 0.061281743366825236, 'reg_lambda': 0.1936678385852877, 'n_estimators': 85}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   5%|▌         | 5/100 [00:09<03:31,  2.23s/it]

[I 2026-08-17 17:52:13,878] Trial 4 finished with value: 0.5046840198574345 and parameters: {'learning_rate': 0.04418763066701282, 'num_leaves': 17, 'max_depth': 7, 'min_child_samples': 26, 'subsample': 0.8717896003373689, 'colsample_bytree': 0.9082794780484345, 'reg_alpha': 0.34349782487170655, 'reg_lambda': 0.948066982357295, 'n_estimators': 268}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   6%|▌         | 6/100 [00:10<02:42,  1.72s/it]

[I 2026-08-17 17:52:14,615] Trial 5 finished with value: 0.5286228449669641 and parameters: {'learning_rate': 0.08453912210208658, 'num_leaves': 13, 'max_depth': 6, 'min_child_samples': 28, 'subsample': 0.955020287488729, 'colsample_bytree': 0.5003876037065482, 'reg_alpha': 0.5519589070648844, 'reg_lambda': 0.8366580759816773, 'n_estimators': 75}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   7%|▋         | 7/100 [00:10<02:12,  1.42s/it]

[I 2026-08-17 17:52:15,414] Trial 6 finished with value: 0.5397449169908548 and parameters: {'learning_rate': 0.05983697287997021, 'num_leaves': 11, 'max_depth': 7, 'min_child_samples': 8, 'subsample': 0.912654172479666, 'colsample_bytree': 0.7314812433140193, 'reg_alpha': 0.09758724296676391, 'reg_lambda': 0.3753387068660401, 'n_estimators': 57}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   8%|▊         | 8/100 [00:12<02:21,  1.54s/it]

[I 2026-08-17 17:52:17,211] Trial 7 finished with value: 0.5915464973465674 and parameters: {'learning_rate': 0.019948306470441372, 'num_leaves': 15, 'max_depth': 8, 'min_child_samples': 23, 'subsample': 0.6182045148843416, 'colsample_bytree': 0.6335475731675362, 'reg_alpha': 0.6563969676050394, 'reg_lambda': 0.30571633061569214, 'n_estimators': 128}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:   9%|▉         | 9/100 [00:14<02:25,  1.60s/it]

[I 2026-08-17 17:52:18,949] Trial 8 finished with value: 0.5294255467131025 and parameters: {'learning_rate': 0.049190576565529054, 'num_leaves': 10, 'max_depth': 5, 'min_child_samples': 44, 'subsample': 0.9393863365913357, 'colsample_bytree': 0.8180335261969254, 'reg_alpha': 0.2668533345784647, 'reg_lambda': 0.9528474098947182, 'n_estimators': 163}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:  10%|█         | 10/100 [00:16<02:26,  1.63s/it]

[I 2026-08-17 17:52:20,633] Trial 9 finished with value: 0.5272540265259199 and parameters: {'learning_rate': 0.03485069643612748, 'num_leaves': 26, 'max_depth': 2, 'min_child_samples': 40, 'subsample': 0.9525527304752566, 'colsample_bytree': 0.8644850138378127, 'reg_alpha': 0.6651316590431982, 'reg_lambda': 0.4511197571476723, 'n_estimators': 286}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 2. Best value: 0.631338:  11%|█         | 11/100 [00:18<02:38,  1.78s/it]

[I 2026-08-17 17:52:22,752] Trial 10 finished with value: 0.5168467156797554 and parameters: {'learning_rate': 0.19074007903011955, 'num_leaves': 22, 'max_depth': 4, 'min_child_samples': 36, 'subsample': 0.7715709349909251, 'colsample_bytree': 0.9713894032285376, 'reg_alpha': 0.940587812609289, 'reg_lambda': 0.08875621902719755, 'n_estimators': 219}. Best is trial 2 with value: 0.6313377828831057.


Best trial: 11. Best value: 0.6463:  12%|█▏        | 12/100 [00:18<02:09,  1.47s/it] 

[I 2026-08-17 17:52:23,519] Trial 11 finished with value: 0.6462996029516161 and parameters: {'learning_rate': 0.010723671804955294, 'num_leaves': 4, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.5084962203502856, 'colsample_bytree': 0.6618049677262159, 'reg_alpha': 0.9955547921480481, 'reg_lambda': 0.2464666112454254, 'n_estimators': 122}. Best is trial 11 with value: 0.6462996029516161.


Best trial: 11. Best value: 0.6463:  13%|█▎        | 13/100 [00:19<01:47,  1.23s/it]

[I 2026-08-17 17:52:24,196] Trial 12 finished with value: 0.6198615425445902 and parameters: {'learning_rate': 0.010473165767921932, 'num_leaves': 4, 'max_depth': 8, 'min_child_samples': 16, 'subsample': 0.7682266830037915, 'colsample_bytree': 0.7525150792582439, 'reg_alpha': 0.9692650698490284, 'reg_lambda': 0.0017229875269231532, 'n_estimators': 116}. Best is trial 11 with value: 0.6462996029516161.


Best trial: 13. Best value: 0.652176:  14%|█▍        | 14/100 [00:20<01:34,  1.10s/it]

[I 2026-08-17 17:52:24,992] Trial 13 finished with value: 0.6521763076582212 and parameters: {'learning_rate': 0.010262665331270753, 'num_leaves': 4, 'max_depth': 7, 'min_child_samples': 35, 'subsample': 0.8152783350293068, 'colsample_bytree': 0.6410146941269009, 'reg_alpha': 0.8444606857969652, 'reg_lambda': 0.2350084390108675, 'n_estimators': 127}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  15%|█▌        | 15/100 [00:21<01:24,  1.01it/s]

[I 2026-08-17 17:52:25,725] Trial 14 finished with value: 0.640634514066085 and parameters: {'learning_rate': 0.017594090384631108, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 47, 'subsample': 0.500546584114181, 'colsample_bytree': 0.6230133237930374, 'reg_alpha': 0.8309708271856631, 'reg_lambda': 0.5370181031848512, 'n_estimators': 165}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  16%|█▌        | 16/100 [00:23<01:51,  1.33s/it]

[I 2026-08-17 17:52:27,851] Trial 15 finished with value: 0.5550864339412543 and parameters: {'learning_rate': 0.019980263464399448, 'num_leaves': 7, 'max_depth': 7, 'min_child_samples': 7, 'subsample': 0.7643705819458833, 'colsample_bytree': 0.5905010074245146, 'reg_alpha': 0.8219320394874128, 'reg_lambda': 0.2689634604437143, 'n_estimators': 127}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  17%|█▋        | 17/100 [00:24<01:46,  1.28s/it]

[I 2026-08-17 17:52:29,005] Trial 16 finished with value: 0.6018752336542997 and parameters: {'learning_rate': 0.015074821887955859, 'num_leaves': 8, 'max_depth': 6, 'min_child_samples': 36, 'subsample': 0.5022113665381343, 'colsample_bytree': 0.6844840877328622, 'reg_alpha': 0.8218817000286451, 'reg_lambda': 0.6643966482097551, 'n_estimators': 184}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  18%|█▊        | 18/100 [00:25<01:27,  1.06s/it]

[I 2026-08-17 17:52:29,573] Trial 17 finished with value: 0.6244344110927008 and parameters: {'learning_rate': 0.010337583594160364, 'num_leaves': 7, 'max_depth': 7, 'min_child_samples': 49, 'subsample': 0.6989728808439774, 'colsample_bytree': 0.537575474284122, 'reg_alpha': 0.47925330259088883, 'reg_lambda': 0.22951646415918886, 'n_estimators': 103}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  19%|█▉        | 19/100 [00:25<01:16,  1.06it/s]

[I 2026-08-17 17:52:30,240] Trial 18 finished with value: 0.5455283346230267 and parameters: {'learning_rate': 0.026769188376406135, 'num_leaves': 4, 'max_depth': 4, 'min_child_samples': 22, 'subsample': 0.6929620376732337, 'colsample_bytree': 0.7799834956775694, 'reg_alpha': 0.8622268874569639, 'reg_lambda': 0.08076145156915082, 'n_estimators': 146}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  20%|██        | 20/100 [00:26<01:10,  1.13it/s]

[I 2026-08-17 17:52:30,978] Trial 19 finished with value: 0.6035766097404538 and parameters: {'learning_rate': 0.01383261046654874, 'num_leaves': 9, 'max_depth': 7, 'min_child_samples': 13, 'subsample': 0.825670011899866, 'colsample_bytree': 0.6821815251108981, 'reg_alpha': 0.7438945207666555, 'reg_lambda': 0.3697181620307083, 'n_estimators': 94}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  21%|██        | 21/100 [00:27<01:16,  1.04it/s]

[I 2026-08-17 17:52:32,129] Trial 20 finished with value: 0.5946954120814439 and parameters: {'learning_rate': 0.022979315497795232, 'num_leaves': 20, 'max_depth': 5, 'min_child_samples': 35, 'subsample': 0.5714793091064925, 'colsample_bytree': 0.6219036625770321, 'reg_alpha': 0.9002026975470983, 'reg_lambda': 0.5865340758126256, 'n_estimators': 199}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  22%|██▏       | 22/100 [00:28<01:11,  1.10it/s]

[I 2026-08-17 17:52:32,916] Trial 21 finished with value: 0.6406942869283208 and parameters: {'learning_rate': 0.015831112536593427, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 49, 'subsample': 0.5087944126745668, 'colsample_bytree': 0.6177826762427427, 'reg_alpha': 0.7724626459859183, 'reg_lambda': 0.5520377694655945, 'n_estimators': 162}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  23%|██▎       | 23/100 [00:29<01:06,  1.15it/s]

[I 2026-08-17 17:52:33,685] Trial 22 finished with value: 0.6318077492409354 and parameters: {'learning_rate': 0.014457223859438553, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 42, 'subsample': 0.5411598136002549, 'colsample_bytree': 0.657973739669391, 'reg_alpha': 0.7500384845505941, 'reg_lambda': 0.3559962467898427, 'n_estimators': 144}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  24%|██▍       | 24/100 [00:30<01:09,  1.09it/s]

[I 2026-08-17 17:52:34,717] Trial 23 finished with value: 0.6426111580570146 and parameters: {'learning_rate': 0.013002256236932042, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 50, 'subsample': 0.6635375941588886, 'colsample_bytree': 0.5922407656209929, 'reg_alpha': 0.772484620693572, 'reg_lambda': 0.5053559552768252, 'n_estimators': 235}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  25%|██▌       | 25/100 [00:31<01:19,  1.06s/it]

[I 2026-08-17 17:52:36,097] Trial 24 finished with value: 0.5928762392714945 and parameters: {'learning_rate': 0.012662586663576758, 'num_leaves': 11, 'max_depth': 8, 'min_child_samples': 39, 'subsample': 0.6257760149281161, 'colsample_bytree': 0.5604218848104499, 'reg_alpha': 0.9942080864376444, 'reg_lambda': 0.16629246140453663, 'n_estimators': 256}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  26%|██▌       | 26/100 [00:32<01:22,  1.12s/it]

[I 2026-08-17 17:52:37,361] Trial 25 finished with value: 0.5973857928172329 and parameters: {'learning_rate': 0.010410253443713014, 'num_leaves': 7, 'max_depth': 8, 'min_child_samples': 33, 'subsample': 0.6528135726267571, 'colsample_bytree': 0.7106028492578765, 'reg_alpha': 0.512744709003919, 'reg_lambda': 0.4739662030630353, 'n_estimators': 238}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  27%|██▋       | 27/100 [00:34<01:30,  1.24s/it]

[I 2026-08-17 17:52:38,904] Trial 26 finished with value: 0.5285848041922228 and parameters: {'learning_rate': 0.02537208016764043, 'num_leaves': 12, 'max_depth': 7, 'min_child_samples': 46, 'subsample': 0.7318170805564803, 'colsample_bytree': 0.5831013867011304, 'reg_alpha': 0.891848885454013, 'reg_lambda': 0.7295432720011167, 'n_estimators': 293}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  28%|██▊       | 28/100 [00:35<01:27,  1.21s/it]

[I 2026-08-17 17:52:40,029] Trial 27 finished with value: 0.5228976843818552 and parameters: {'learning_rate': 0.01782762674020032, 'num_leaves': 9, 'max_depth': 8, 'min_child_samples': 25, 'subsample': 0.9935208424569517, 'colsample_bytree': 0.5351816874994626, 'reg_alpha': 0.8976593628879805, 'reg_lambda': 0.28216669178584675, 'n_estimators': 188}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  29%|██▉       | 29/100 [00:36<01:13,  1.03s/it]

[I 2026-08-17 17:52:40,650] Trial 28 finished with value: 0.5972392958268067 and parameters: {'learning_rate': 0.01287821334692289, 'num_leaves': 6, 'max_depth': 7, 'min_child_samples': 18, 'subsample': 0.7959711444908847, 'colsample_bytree': 0.5025377473826881, 'reg_alpha': 0.6016772666130991, 'reg_lambda': 0.08725021996664856, 'n_estimators': 103}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  30%|███       | 30/100 [00:38<01:36,  1.37s/it]

[I 2026-08-17 17:52:42,814] Trial 29 finished with value: 0.5418328930484408 and parameters: {'learning_rate': 0.010077072746815706, 'num_leaves': 14, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.5594010892399465, 'colsample_bytree': 0.659145967436205, 'reg_alpha': 0.7385975085464747, 'reg_lambda': 0.4678068582036236, 'n_estimators': 235}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  31%|███       | 31/100 [00:39<01:23,  1.21s/it]

[I 2026-08-17 17:52:43,663] Trial 30 finished with value: 0.5015265865401807 and parameters: {'learning_rate': 0.09624033333316634, 'num_leaves': 9, 'max_depth': 5, 'min_child_samples': 38, 'subsample': 0.7240503033711475, 'colsample_bytree': 0.7885650098613034, 'reg_alpha': 0.45203565249784133, 'reg_lambda': 0.40898759848397986, 'n_estimators': 146}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  32%|███▏      | 32/100 [00:39<01:13,  1.08s/it]

[I 2026-08-17 17:52:44,425] Trial 31 finished with value: 0.6400150449430988 and parameters: {'learning_rate': 0.015649997532185555, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 50, 'subsample': 0.5372856379583529, 'colsample_bytree': 0.608529779876182, 'reg_alpha': 0.7821556537148325, 'reg_lambda': 0.5585663046936785, 'n_estimators': 173}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  33%|███▎      | 33/100 [00:40<01:02,  1.07it/s]

[I 2026-08-17 17:52:45,030] Trial 32 finished with value: 0.6402048663734519 and parameters: {'learning_rate': 0.01680394720116979, 'num_leaves': 5, 'max_depth': 7, 'min_child_samples': 44, 'subsample': 0.6573297086728846, 'colsample_bytree': 0.643991362914448, 'reg_alpha': 0.6950401682482487, 'reg_lambda': 0.6285298212225784, 'n_estimators': 121}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  34%|███▍      | 34/100 [00:41<00:57,  1.14it/s]

[I 2026-08-17 17:52:45,758] Trial 33 finished with value: 0.6373929835366521 and parameters: {'learning_rate': 0.012382722099905631, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 47, 'subsample': 0.530730768708893, 'colsample_bytree': 0.5911250083675373, 'reg_alpha': 0.7984122886686393, 'reg_lambda': 0.5276492912263316, 'n_estimators': 145}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  35%|███▌      | 35/100 [00:42<00:56,  1.15it/s]

[I 2026-08-17 17:52:46,610] Trial 34 finished with value: 0.606082645974875 and parameters: {'learning_rate': 0.021193033190717605, 'num_leaves': 4, 'max_depth': 8, 'min_child_samples': 30, 'subsample': 0.5890751690461264, 'colsample_bytree': 0.6966393558741071, 'reg_alpha': 0.9279623876180012, 'reg_lambda': 0.7385223668572017, 'n_estimators': 214}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  36%|███▌      | 36/100 [00:42<00:50,  1.28it/s]

[I 2026-08-17 17:52:47,195] Trial 35 finished with value: 0.6027562391920259 and parameters: {'learning_rate': 0.028029923847310102, 'num_leaves': 8, 'max_depth': 7, 'min_child_samples': 42, 'subsample': 0.8604210084171855, 'colsample_bytree': 0.5554042214324906, 'reg_alpha': 0.9978778920233754, 'reg_lambda': 0.6533712150223666, 'n_estimators': 79}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  37%|███▋      | 37/100 [00:43<00:55,  1.13it/s]

[I 2026-08-17 17:52:48,327] Trial 36 finished with value: 0.6429652419086355 and parameters: {'learning_rate': 0.011950028342198505, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 50, 'subsample': 0.6015268250383907, 'colsample_bytree': 0.6569253944990673, 'reg_alpha': 0.702344477347156, 'reg_lambda': 0.8547564129798623, 'n_estimators': 271}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  38%|███▊      | 38/100 [00:45<01:07,  1.09s/it]

[I 2026-08-17 17:52:49,907] Trial 37 finished with value: 0.5975747815246037 and parameters: {'learning_rate': 0.01272564639521211, 'num_leaves': 8, 'max_depth': 8, 'min_child_samples': 33, 'subsample': 0.6247920528673303, 'colsample_bytree': 0.7282643795351658, 'reg_alpha': 0.5986467630610011, 'reg_lambda': 0.8975459934519207, 'n_estimators': 273}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  39%|███▉      | 39/100 [00:47<01:19,  1.30s/it]

[I 2026-08-17 17:52:51,700] Trial 38 finished with value: 0.5260256108064907 and parameters: {'learning_rate': 0.011530954768595131, 'num_leaves': 11, 'max_depth': 8, 'min_child_samples': 21, 'subsample': 0.5689245098106024, 'colsample_bytree': 0.664934646953479, 'reg_alpha': 0.7102229096497179, 'reg_lambda': 0.8554455798160403, 'n_estimators': 254}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  40%|████      | 40/100 [00:48<01:15,  1.26s/it]

[I 2026-08-17 17:52:52,842] Trial 39 finished with value: 0.6154449752937661 and parameters: {'learning_rate': 0.011865050334242871, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 27, 'subsample': 0.6637789165912149, 'colsample_bytree': 0.7108798146722071, 'reg_alpha': 0.6120631562596667, 'reg_lambda': 0.7950456138127011, 'n_estimators': 228}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  41%|████      | 41/100 [00:50<01:24,  1.43s/it]

[I 2026-08-17 17:52:54,689] Trial 40 finished with value: 0.5384701825538183 and parameters: {'learning_rate': 0.018637386779158105, 'num_leaves': 10, 'max_depth': 7, 'min_child_samples': 44, 'subsample': 0.9046164262805398, 'colsample_bytree': 0.6457054435939744, 'reg_alpha': 0.8450958624947933, 'reg_lambda': 0.21773961929320612, 'n_estimators': 276}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  42%|████▏     | 42/100 [00:51<01:26,  1.49s/it]

[I 2026-08-17 17:52:56,330] Trial 41 finished with value: 0.6363759256624514 and parameters: {'learning_rate': 0.015260382532433425, 'num_leaves': 5, 'max_depth': 8, 'min_child_samples': 50, 'subsample': 0.602117058608947, 'colsample_bytree': 0.6128668247892722, 'reg_alpha': 0.7757094028098748, 'reg_lambda': 0.3209554137849203, 'n_estimators': 111}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  43%|████▎     | 43/100 [00:52<01:17,  1.35s/it]

[I 2026-08-17 17:52:57,354] Trial 42 finished with value: 0.6094241959125742 and parameters: {'learning_rate': 0.014241635345178071, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 48, 'subsample': 0.540549290990563, 'colsample_bytree': 0.5748867408336924, 'reg_alpha': 0.8767808111342901, 'reg_lambda': 0.9827344166775535, 'n_estimators': 259}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  44%|████▍     | 44/100 [00:53<01:05,  1.16s/it]

[I 2026-08-17 17:52:58,066] Trial 43 finished with value: 0.6327893563345027 and parameters: {'learning_rate': 0.011408705816114424, 'num_leaves': 7, 'max_depth': 7, 'min_child_samples': 45, 'subsample': 0.518214015565986, 'colsample_bytree': 0.6062539593761299, 'reg_alpha': 0.6671267670435523, 'reg_lambda': 0.4243386208282627, 'n_estimators': 132}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  45%|████▌     | 45/100 [00:55<01:10,  1.28s/it]

[I 2026-08-17 17:52:59,632] Trial 44 finished with value: 0.5220190551266016 and parameters: {'learning_rate': 0.033153026622459884, 'num_leaves': 5, 'max_depth': 8, 'min_child_samples': 42, 'subsample': 0.5571669234830522, 'colsample_bytree': 0.6358424859508883, 'reg_alpha': 0.9482121435411608, 'reg_lambda': 0.7804275697653289, 'n_estimators': 300}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  46%|████▌     | 46/100 [00:55<01:02,  1.16s/it]

[I 2026-08-17 17:53:00,516] Trial 45 finished with value: 0.6442542138798047 and parameters: {'learning_rate': 0.01657154941296127, 'num_leaves': 6, 'max_depth': 4, 'min_child_samples': 49, 'subsample': 0.5926712693473193, 'colsample_bytree': 0.7501170331617054, 'reg_alpha': 0.7060426660329746, 'reg_lambda': 0.15183100788156323, 'n_estimators': 159}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 13. Best value: 0.652176:  47%|████▋     | 47/100 [00:56<00:50,  1.06it/s]

[I 2026-08-17 17:53:00,959] Trial 46 finished with value: 0.6416565823325158 and parameters: {'learning_rate': 0.013597140550893106, 'num_leaves': 30, 'max_depth': 3, 'min_child_samples': 41, 'subsample': 0.6081584042163508, 'colsample_bytree': 0.7589878794717515, 'reg_alpha': 0.22057565995758455, 'reg_lambda': 0.032111522107100915, 'n_estimators': 52}. Best is trial 13 with value: 0.6521763076582212.


Best trial: 47. Best value: 0.662938:  48%|████▊     | 48/100 [00:56<00:41,  1.25it/s]

[I 2026-08-17 17:53:01,415] Trial 47 finished with value: 0.6629377031368289 and parameters: {'learning_rate': 0.02203790088281373, 'num_leaves': 8, 'max_depth': 2, 'min_child_samples': 5, 'subsample': 0.6407412661570229, 'colsample_bytree': 0.8764860498747737, 'reg_alpha': 0.5623346762562627, 'reg_lambda': 0.13634626286220186, 'n_estimators': 64}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  49%|████▉     | 49/100 [00:57<00:35,  1.44it/s]

[I 2026-08-17 17:53:01,866] Trial 48 finished with value: 0.6616317560510101 and parameters: {'learning_rate': 0.021965133907660753, 'num_leaves': 10, 'max_depth': 2, 'min_child_samples': 5, 'subsample': 0.6380108779269922, 'colsample_bytree': 0.9151243283725939, 'reg_alpha': 0.4011199558672555, 'reg_lambda': 0.1412928282472054, 'n_estimators': 63}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  50%|█████     | 50/100 [00:57<00:31,  1.56it/s]

[I 2026-08-17 17:53:02,376] Trial 49 finished with value: 0.5610965378335945 and parameters: {'learning_rate': 0.03016453402648605, 'num_leaves': 12, 'max_depth': 2, 'min_child_samples': 5, 'subsample': 0.6405710775504863, 'colsample_bytree': 0.96528182390495, 'reg_alpha': 0.43886209690304756, 'reg_lambda': 0.1342463580050766, 'n_estimators': 72}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  51%|█████     | 51/100 [00:58<00:34,  1.43it/s]

[I 2026-08-17 17:53:03,215] Trial 50 finished with value: 0.5429612581984523 and parameters: {'learning_rate': 0.02329612118508522, 'num_leaves': 17, 'max_depth': 3, 'min_child_samples': 12, 'subsample': 0.714592884934474, 'colsample_bytree': 0.9030307459689593, 'reg_alpha': 0.3962773642914178, 'reg_lambda': 0.13445422172349614, 'n_estimators': 91}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  52%|█████▏    | 52/100 [00:59<00:31,  1.52it/s]

[I 2026-08-17 17:53:03,570] Trial 51 finished with value: 0.6245302630436744 and parameters: {'learning_rate': 0.020836538850738905, 'num_leaves': 10, 'max_depth': 2, 'min_child_samples': 8, 'subsample': 0.5953570904759883, 'colsample_bytree': 0.84314643932194, 'reg_alpha': 0.5474261428678414, 'reg_lambda': 0.24533253293501, 'n_estimators': 65}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  53%|█████▎    | 53/100 [01:01<00:48,  1.03s/it]

[I 2026-08-17 17:53:05,672] Trial 52 finished with value: 0.6360621307501116 and parameters: {'learning_rate': 0.01773682636532543, 'num_leaves': 8, 'max_depth': 3, 'min_child_samples': 5, 'subsample': 0.5833048684930782, 'colsample_bytree': 0.9237565279178998, 'reg_alpha': 0.2883809487938041, 'reg_lambda': 0.17727935492349173, 'n_estimators': 83}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  54%|█████▍    | 54/100 [01:06<01:41,  2.20s/it]

[I 2026-08-17 17:53:10,605] Trial 53 finished with value: 0.529225665744012 and parameters: {'learning_rate': 0.04156420995892819, 'num_leaves': 9, 'max_depth': 4, 'min_child_samples': 15, 'subsample': 0.7461126585957011, 'colsample_bytree': 0.9991919717549053, 'reg_alpha': 0.16216285876849387, 'reg_lambda': 0.13202756234849433, 'n_estimators': 67}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  55%|█████▌    | 55/100 [01:07<01:23,  1.85s/it]

[I 2026-08-17 17:53:11,624] Trial 54 finished with value: 0.6600268759831446 and parameters: {'learning_rate': 0.023826041957089174, 'num_leaves': 7, 'max_depth': 2, 'min_child_samples': 11, 'subsample': 0.6910117051365215, 'colsample_bytree': 0.8616933561206661, 'reg_alpha': 0.3874085513419743, 'reg_lambda': 0.04978881268083782, 'n_estimators': 51}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  56%|█████▌    | 56/100 [01:08<01:19,  1.81s/it]

[I 2026-08-17 17:53:13,328] Trial 55 finished with value: 0.552609200503914 and parameters: {'learning_rate': 0.03863937292054983, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 11, 'subsample': 0.6338547928339566, 'colsample_bytree': 0.8796496350866025, 'reg_alpha': 0.33976165886889165, 'reg_lambda': 0.043493023253453056, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  57%|█████▋    | 57/100 [01:10<01:11,  1.67s/it]

[I 2026-08-17 17:53:14,686] Trial 56 finished with value: 0.5463613230972456 and parameters: {'learning_rate': 0.02456235856371998, 'num_leaves': 27, 'max_depth': 3, 'min_child_samples': 7, 'subsample': 0.6898018961183258, 'colsample_bytree': 0.8286893416457372, 'reg_alpha': 0.5589005667675282, 'reg_lambda': 0.20564548295025667, 'n_estimators': 60}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  58%|█████▊    | 58/100 [01:12<01:21,  1.94s/it]

[I 2026-08-17 17:53:17,259] Trial 57 finished with value: 0.5534689890410898 and parameters: {'learning_rate': 0.030216200759237487, 'num_leaves': 7, 'max_depth': 2, 'min_child_samples': 9, 'subsample': 0.7959731781135664, 'colsample_bytree': 0.8945196144790711, 'reg_alpha': 0.40810614748907004, 'reg_lambda': 0.050663057725602284, 'n_estimators': 97}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  59%|█████▉    | 59/100 [01:13<01:09,  1.70s/it]

[I 2026-08-17 17:53:18,409] Trial 58 finished with value: 0.5470903359352958 and parameters: {'learning_rate': 0.019796694070990512, 'num_leaves': 4, 'max_depth': 2, 'min_child_samples': 18, 'subsample': 0.6835380808612024, 'colsample_bytree': 0.9425483755814426, 'reg_alpha': 0.4928407234638883, 'reg_lambda': 0.1177707497044886, 'n_estimators': 133}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  60%|██████    | 60/100 [01:16<01:16,  1.92s/it]

[I 2026-08-17 17:53:20,839] Trial 59 finished with value: 0.4963790966430229 and parameters: {'learning_rate': 0.15280203061657613, 'num_leaves': 10, 'max_depth': 3, 'min_child_samples': 6, 'subsample': 0.6739088336263226, 'colsample_bytree': 0.8089597543633746, 'reg_alpha': 0.34696801293740426, 'reg_lambda': 0.2583709465863294, 'n_estimators': 112}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  61%|██████    | 61/100 [01:17<01:09,  1.79s/it]

[I 2026-08-17 17:53:22,328] Trial 60 finished with value: 0.6169812009034612 and parameters: {'learning_rate': 0.021072844932776186, 'num_leaves': 7, 'max_depth': 4, 'min_child_samples': 13, 'subsample': 0.702453244846973, 'colsample_bytree': 0.8698396368279073, 'reg_alpha': 0.009510827466671645, 'reg_lambda': 0.31739440645723527, 'n_estimators': 74}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  62%|██████▏   | 62/100 [01:20<01:17,  2.05s/it]

[I 2026-08-17 17:53:24,983] Trial 61 finished with value: 0.657639516450998 and parameters: {'learning_rate': 0.011199295200741397, 'num_leaves': 6, 'max_depth': 2, 'min_child_samples': 16, 'subsample': 0.6104614985610293, 'colsample_bytree': 0.849120834907593, 'reg_alpha': 0.6578004160513664, 'reg_lambda': 0.17476645992680223, 'n_estimators': 60}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  63%|██████▎   | 63/100 [01:21<01:08,  1.85s/it]

[I 2026-08-17 17:53:26,351] Trial 62 finished with value: 0.6461567864946712 and parameters: {'learning_rate': 0.01085208752023459, 'num_leaves': 8, 'max_depth': 2, 'min_child_samples': 16, 'subsample': 0.6177511882354342, 'colsample_bytree': 0.843056400865118, 'reg_alpha': 0.53170870487213, 'reg_lambda': 6.386247577866433e-05, 'n_estimators': 157}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  64%|██████▍   | 64/100 [01:22<00:53,  1.49s/it]

[I 2026-08-17 17:53:27,013] Trial 63 finished with value: 0.6496370412485228 and parameters: {'learning_rate': 0.01116948162138589, 'num_leaves': 8, 'max_depth': 2, 'min_child_samples': 14, 'subsample': 0.6432849629330021, 'colsample_bytree': 0.8516137480982533, 'reg_alpha': 0.5293748004145029, 'reg_lambda': 0.01639955974408968, 'n_estimators': 87}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  65%|██████▌   | 65/100 [01:23<00:42,  1.22s/it]

[I 2026-08-17 17:53:27,586] Trial 64 finished with value: 0.6500249291364107 and parameters: {'learning_rate': 0.010126536169277738, 'num_leaves': 12, 'max_depth': 2, 'min_child_samples': 14, 'subsample': 0.6380147766626781, 'colsample_bytree': 0.9206827553890325, 'reg_alpha': 0.6362396489572559, 'reg_lambda': 0.1027184745688956, 'n_estimators': 87}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  66%|██████▌   | 66/100 [01:23<00:35,  1.05s/it]

[I 2026-08-17 17:53:28,246] Trial 65 finished with value: 0.5380075922227073 and parameters: {'learning_rate': 0.05216876322362238, 'num_leaves': 16, 'max_depth': 2, 'min_child_samples': 10, 'subsample': 0.6405244827572834, 'colsample_bytree': 0.8812770350968793, 'reg_alpha': 0.6388990714369406, 'reg_lambda': 0.08953110041807102, 'n_estimators': 88}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  67%|██████▋   | 67/100 [01:24<00:30,  1.08it/s]

[I 2026-08-17 17:53:28,895] Trial 66 finished with value: 0.647735139346621 and parameters: {'learning_rate': 0.01010449524792332, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 15, 'subsample': 0.6526809540962571, 'colsample_bytree': 0.9320329741006484, 'reg_alpha': 0.5733605523737437, 'reg_lambda': 0.18678394122352004, 'n_estimators': 60}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  68%|██████▊   | 68/100 [01:25<00:29,  1.09it/s]

[I 2026-08-17 17:53:29,791] Trial 67 finished with value: 0.6369794435124512 and parameters: {'learning_rate': 0.014355123325367208, 'num_leaves': 12, 'max_depth': 3, 'min_child_samples': 24, 'subsample': 0.6782457348795214, 'colsample_bytree': 0.8518628253160166, 'reg_alpha': 0.4705571506623921, 'reg_lambda': 0.06648553186849351, 'n_estimators': 70}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  69%|██████▉   | 69/100 [01:25<00:25,  1.23it/s]

[I 2026-08-17 17:53:30,354] Trial 68 finished with value: 0.5346499267403229 and parameters: {'learning_rate': 0.06541518128982764, 'num_leaves': 14, 'max_depth': 2, 'min_child_samples': 17, 'subsample': 0.6145913810731253, 'colsample_bytree': 0.9145439587815344, 'reg_alpha': 0.3788586253429252, 'reg_lambda': 0.10301530764673476, 'n_estimators': 80}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  70%|███████   | 70/100 [01:26<00:22,  1.34it/s]

[I 2026-08-17 17:53:30,950] Trial 69 finished with value: 0.5531321973175298 and parameters: {'learning_rate': 0.027758542637408307, 'num_leaves': 10, 'max_depth': 2, 'min_child_samples': 13, 'subsample': 0.7472129690694098, 'colsample_bytree': 0.9504667435592961, 'reg_alpha': 0.638895025510168, 'reg_lambda': 0.02267580541080333, 'n_estimators': 100}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  71%|███████   | 71/100 [01:28<00:30,  1.04s/it]

[I 2026-08-17 17:53:32,667] Trial 70 finished with value: 0.5464543372966643 and parameters: {'learning_rate': 0.033271046215634384, 'num_leaves': 11, 'max_depth': 3, 'min_child_samples': 9, 'subsample': 0.8599866039470931, 'colsample_bytree': 0.7981654110612352, 'reg_alpha': 0.4374955402521624, 'reg_lambda': 0.06659917338713708, 'n_estimators': 57}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  72%|███████▏  | 72/100 [01:28<00:24,  1.13it/s]

[I 2026-08-17 17:53:33,200] Trial 71 finished with value: 0.658226057577598 and parameters: {'learning_rate': 0.010871162199370557, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.6446571791672716, 'colsample_bytree': 0.9303257881432091, 'reg_alpha': 0.5739430500247642, 'reg_lambda': 0.1786021591521626, 'n_estimators': 57}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  73%|███████▎  | 73/100 [01:29<00:21,  1.26it/s]

[I 2026-08-17 17:53:33,769] Trial 72 finished with value: 0.655704280869053 and parameters: {'learning_rate': 0.011249132097716243, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 19, 'subsample': 0.6445845592457861, 'colsample_bytree': 0.9032826698358447, 'reg_alpha': 0.5090845382744288, 'reg_lambda': 0.1659695427167553, 'n_estimators': 51}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  74%|███████▍  | 74/100 [01:29<00:17,  1.45it/s]

[I 2026-08-17 17:53:34,229] Trial 73 finished with value: 0.658226057577598 and parameters: {'learning_rate': 0.013406548385658228, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.6672752159530196, 'colsample_bytree': 0.8917086631505539, 'reg_alpha': 0.4990219842503994, 'reg_lambda': 0.29117845799069214, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  75%|███████▌  | 75/100 [01:30<00:15,  1.64it/s]

[I 2026-08-17 17:53:34,646] Trial 74 finished with value: 0.655195754547295 and parameters: {'learning_rate': 0.013615691398867927, 'num_leaves': 18, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.7052124540445728, 'colsample_bytree': 0.8923771694176625, 'reg_alpha': 0.47586895052127687, 'reg_lambda': 0.28345490045034955, 'n_estimators': 53}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  76%|███████▌  | 76/100 [01:30<00:13,  1.83it/s]

[I 2026-08-17 17:53:35,048] Trial 75 finished with value: 0.658226057577598 and parameters: {'learning_rate': 0.013550570656151385, 'num_leaves': 18, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.7039351661316551, 'colsample_bytree': 0.8919483830020357, 'reg_alpha': 0.5013512522159824, 'reg_lambda': 0.33616243876394747, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  77%|███████▋  | 77/100 [01:30<00:11,  1.93it/s]

[I 2026-08-17 17:53:35,501] Trial 76 finished with value: 0.6535384280475841 and parameters: {'learning_rate': 0.015841482791207936, 'num_leaves': 19, 'max_depth': 2, 'min_child_samples': 22, 'subsample': 0.6727028382652607, 'colsample_bytree': 0.825948896683967, 'reg_alpha': 0.5111865785068361, 'reg_lambda': 0.3351716971778578, 'n_estimators': 63}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  78%|███████▊  | 78/100 [01:31<00:10,  2.00it/s]

[I 2026-08-17 17:53:35,954] Trial 77 finished with value: 0.6524606566767289 and parameters: {'learning_rate': 0.022757228140813573, 'num_leaves': 22, 'max_depth': 2, 'min_child_samples': 19, 'subsample': 0.6591499287494808, 'colsample_bytree': 0.8726963916737702, 'reg_alpha': 0.5859853553291757, 'reg_lambda': 0.208684415548287, 'n_estimators': 57}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  79%|███████▉  | 79/100 [01:31<00:10,  2.02it/s]

[I 2026-08-17 17:53:36,444] Trial 78 finished with value: 0.6529190518564439 and parameters: {'learning_rate': 0.01822287403136686, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 23, 'subsample': 0.7250830061570213, 'colsample_bytree': 0.9062489241841842, 'reg_alpha': 0.4177035784906097, 'reg_lambda': 0.16143012039187776, 'n_estimators': 77}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  80%|████████  | 80/100 [01:32<00:10,  1.89it/s]

[I 2026-08-17 17:53:37,046] Trial 79 finished with value: 0.6355332828771476 and parameters: {'learning_rate': 0.012466538882639535, 'num_leaves': 16, 'max_depth': 3, 'min_child_samples': 20, 'subsample': 0.6262621104081905, 'colsample_bytree': 0.8896137567093999, 'reg_alpha': 0.3692324417723389, 'reg_lambda': 0.30064060147273286, 'n_estimators': 68}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  81%|████████  | 81/100 [01:32<00:09,  1.95it/s]

[I 2026-08-17 17:53:37,517] Trial 80 finished with value: 0.6518238212576964 and parameters: {'learning_rate': 0.019444707314197115, 'num_leaves': 21, 'max_depth': 2, 'min_child_samples': 26, 'subsample': 0.7083991994418668, 'colsample_bytree': 0.9354173953701068, 'reg_alpha': 0.5032658468305542, 'reg_lambda': 0.38733331527014836, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  82%|████████▏ | 82/100 [01:33<00:08,  2.05it/s]

[I 2026-08-17 17:53:37,949] Trial 81 finished with value: 0.6540463292599386 and parameters: {'learning_rate': 0.013584482707381485, 'num_leaves': 19, 'max_depth': 2, 'min_child_samples': 19, 'subsample': 0.6954279590699367, 'colsample_bytree': 0.8948700552165336, 'reg_alpha': 0.4732962223339623, 'reg_lambda': 0.27904302454412455, 'n_estimators': 53}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  83%|████████▎ | 83/100 [01:33<00:08,  2.04it/s]

[I 2026-08-17 17:53:38,441] Trial 82 finished with value: 0.6507060744173582 and parameters: {'learning_rate': 0.014969984864711038, 'num_leaves': 18, 'max_depth': 2, 'min_child_samples': 21, 'subsample': 0.6659583917997209, 'colsample_bytree': 0.9617590680398507, 'reg_alpha': 0.2941311044399229, 'reg_lambda': 0.34675560256983967, 'n_estimators': 61}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  84%|████████▍ | 84/100 [01:34<00:08,  1.95it/s]

[I 2026-08-17 17:53:39,008] Trial 83 finished with value: 0.6468342384457201 and parameters: {'learning_rate': 0.01645345209624741, 'num_leaves': 17, 'max_depth': 2, 'min_child_samples': 17, 'subsample': 0.7389842209811414, 'colsample_bytree': 0.9056314784188281, 'reg_alpha': 0.4682949885412516, 'reg_lambda': 0.23580449049737603, 'n_estimators': 56}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  85%|████████▌ | 85/100 [01:35<00:11,  1.30it/s]

[I 2026-08-17 17:53:40,365] Trial 84 finished with value: 0.6514789891925984 and parameters: {'learning_rate': 0.013363076198005648, 'num_leaves': 16, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.7109908988270192, 'colsample_bytree': 0.8585757827924294, 'reg_alpha': 0.5381309447737884, 'reg_lambda': 0.29062800472344796, 'n_estimators': 73}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  86%|████████▌ | 86/100 [01:38<00:18,  1.35s/it]

[I 2026-08-17 17:53:43,042] Trial 85 finished with value: 0.6295588075432039 and parameters: {'learning_rate': 0.011764185051025083, 'num_leaves': 14, 'max_depth': 3, 'min_child_samples': 23, 'subsample': 0.6491571064987623, 'colsample_bytree': 0.8836142855345817, 'reg_alpha': 0.5650773674267616, 'reg_lambda': 0.19004567228722896, 'n_estimators': 65}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  87%|████████▋ | 87/100 [01:39<00:15,  1.17s/it]

[I 2026-08-17 17:53:43,568] Trial 86 finished with value: 0.6518814856929672 and parameters: {'learning_rate': 0.010921364190105278, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 18, 'subsample': 0.6804396643357419, 'colsample_bytree': 0.8651164417656823, 'reg_alpha': 0.6092594872063373, 'reg_lambda': 0.1647500173103979, 'n_estimators': 78}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  88%|████████▊ | 88/100 [01:39<00:12,  1.02s/it]

[I 2026-08-17 17:53:44,495] Trial 87 finished with value: 0.650536574090242 and parameters: {'learning_rate': 0.014726793372573713, 'num_leaves': 18, 'max_depth': 2, 'min_child_samples': 20, 'subsample': 0.6895512911877496, 'colsample_bytree': 0.984472102877261, 'reg_alpha': 0.45459079666012114, 'reg_lambda': 0.26814524142777574, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  89%|████████▉ | 89/100 [01:40<00:09,  1.11it/s]

[I 2026-08-17 17:53:45,123] Trial 88 finished with value: 0.6509384418305137 and parameters: {'learning_rate': 0.025037724109074067, 'num_leaves': 18, 'max_depth': 2, 'min_child_samples': 22, 'subsample': 0.6663484252463744, 'colsample_bytree': 0.9487629618921692, 'reg_alpha': 0.42455761966025796, 'reg_lambda': 0.22206189353822467, 'n_estimators': 66}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  90%|█████████ | 90/100 [01:41<00:08,  1.12it/s]

[I 2026-08-17 17:53:46,002] Trial 89 finished with value: 0.6085138422946121 and parameters: {'learning_rate': 0.01724487675580886, 'num_leaves': 19, 'max_depth': 3, 'min_child_samples': 7, 'subsample': 0.7596600513494539, 'colsample_bytree': 0.9272693155418447, 'reg_alpha': 0.6685996888533178, 'reg_lambda': 0.3743412563115587, 'n_estimators': 57}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  91%|█████████ | 91/100 [01:42<00:07,  1.24it/s]

[I 2026-08-17 17:53:46,595] Trial 90 finished with value: 0.6495416458531275 and parameters: {'learning_rate': 0.011823577164724349, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 15, 'subsample': 0.7214567521236277, 'colsample_bytree': 0.8350969317350768, 'reg_alpha': 0.33612995247534494, 'reg_lambda': 0.15137825089384271, 'n_estimators': 72}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  92%|█████████▏| 92/100 [01:42<00:05,  1.34it/s]

[I 2026-08-17 17:53:47,212] Trial 91 finished with value: 0.6550589798415547 and parameters: {'learning_rate': 0.01321047241693887, 'num_leaves': 20, 'max_depth': 2, 'min_child_samples': 19, 'subsample': 0.6294059861407337, 'colsample_bytree': 0.8944134947019273, 'reg_alpha': 0.5181005742534706, 'reg_lambda': 0.27989093641183094, 'n_estimators': 54}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  93%|█████████▎| 93/100 [01:43<00:04,  1.46it/s]

[I 2026-08-17 17:53:47,756] Trial 92 finished with value: 0.6481027069141885 and parameters: {'learning_rate': 0.01286161827902301, 'num_leaves': 24, 'max_depth': 2, 'min_child_samples': 17, 'subsample': 0.578706534415895, 'colsample_bytree': 0.8998489591496889, 'reg_alpha': 0.5132385542821571, 'reg_lambda': 0.2557779734006427, 'n_estimators': 62}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  94%|█████████▍| 94/100 [01:43<00:03,  1.57it/s]

[I 2026-08-17 17:53:48,275] Trial 93 finished with value: 0.6534942135769259 and parameters: {'learning_rate': 0.022083544957038802, 'num_leaves': 20, 'max_depth': 2, 'min_child_samples': 24, 'subsample': 0.6243779385437486, 'colsample_bytree': 0.9115976058204138, 'reg_alpha': 0.49716269153242454, 'reg_lambda': 0.1978007011098221, 'n_estimators': 55}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  95%|█████████▌| 95/100 [01:44<00:03,  1.58it/s]

[I 2026-08-17 17:53:48,889] Trial 94 finished with value: 0.6544946285796664 and parameters: {'learning_rate': 0.014065526209274214, 'num_leaves': 17, 'max_depth': 2, 'min_child_samples': 19, 'subsample': 0.6089396922908528, 'colsample_bytree': 0.8730757884326205, 'reg_alpha': 0.39142411312103637, 'reg_lambda': 0.43823644420818103, 'n_estimators': 81}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  96%|█████████▌| 96/100 [01:44<00:02,  1.66it/s]

[I 2026-08-17 17:53:49,418] Trial 95 finished with value: 0.6508804846919662 and parameters: {'learning_rate': 0.01087161761452104, 'num_leaves': 21, 'max_depth': 2, 'min_child_samples': 16, 'subsample': 0.6331056147605861, 'colsample_bytree': 0.8899199116827755, 'reg_alpha': 0.5814864781122331, 'reg_lambda': 0.12489500997821355, 'n_estimators': 69}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  97%|█████████▋| 97/100 [01:45<00:01,  1.82it/s]

[I 2026-08-17 17:53:49,860] Trial 96 finished with value: 0.6495601972965568 and parameters: {'learning_rate': 0.012155902466455478, 'num_leaves': 20, 'max_depth': 2, 'min_child_samples': 21, 'subsample': 0.6570311315679364, 'colsample_bytree': 0.8553135971499014, 'reg_alpha': 0.48721189554871963, 'reg_lambda': 0.31224566895710737, 'n_estimators': 61}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 47. Best value: 0.662938:  98%|█████████▊| 98/100 [01:45<00:01,  1.88it/s]

[I 2026-08-17 17:53:50,346] Trial 97 finished with value: 0.5936690426360194 and parameters: {'learning_rate': 0.015614327028767883, 'num_leaves': 23, 'max_depth': 3, 'min_child_samples': 11, 'subsample': 0.649671511781823, 'colsample_bytree': 0.8777707577724464, 'reg_alpha': 0.5532433272999858, 'reg_lambda': 0.234858774719859, 'n_estimators': 50}. Best is trial 47 with value: 0.6629377031368289.


Best trial: 98. Best value: 0.66447:  99%|█████████▉| 99/100 [01:46<00:00,  1.95it/s] 

[I 2026-08-17 17:53:50,822] Trial 98 finished with value: 0.6644702111550511 and parameters: {'learning_rate': 0.01901487700210657, 'num_leaves': 16, 'max_depth': 2, 'min_child_samples': 6, 'subsample': 0.7013003175660778, 'colsample_bytree': 0.8411939035179709, 'reg_alpha': 0.5197599705062297, 'reg_lambda': 0.3366261518757465, 'n_estimators': 56}. Best is trial 98 with value: 0.6644702111550511.


Best trial: 98. Best value: 0.66447:  99%|█████████▉| 99/100 [01:46<00:00,  1.95it/s]

[I 2026-08-17 17:53:51,285] Trial 99 finished with value: 0.6661467795601909 and parameters: {'learning_rate': 0.018909621443467715, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 6, 'subsample': 0.6992340850376021, 'colsample_bytree': 0.8203261117853924, 'reg_alpha': 0.4480047925625076, 'reg_lambda': 0.39004263179543947, 'n_estimators': 66}. Best is trial 99 with value: 0.6661467795601909.


Best trial: 99. Best value: 0.666147: 100%|██████████| 100/100 [01:47<00:00,  1.08s/it]


最佳參數: {'learning_rate': 0.018909621443467715, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 6, 'subsample': 0.6992340850376021, 'colsample_bytree': 0.8203261117853924, 'reg_alpha': 0.4480047925625076, 'reg_lambda': 0.39004263179543947, 'n_estimators': 66}
最佳 CV recall_macro: 0.6661467795601909

=== 開始訓練最終模型 ===

=== 調參後最終模型 ===
train:                precision    recall  f1-score   support

  Cooperation       0.94      0.81      0.87       777
High_Conflict       0.61      0.89      0.72        95
 Low_Conflict       0.52      0.71      0.60       172

     accuracy                           0.80      1044
    macro avg       0.69      0.81      0.73      1044
 weighted avg       0.84      0.80      0.82      1044

test:                precision    recall  f1-score   support

  Cooperation       0.94      0.85      0.89       244
High_Conflict       0.55      0.59      0.57        44
 Low_Conflict       0.64      0.76      0.69       108

     accuracy                         

In [29]:
import optuna
import numpy as np
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import roc_auc_score, classification_report
from sklearn.preprocessing import label_binarize
from lightgbm import LGBMClassifier
from sklearn.utils.class_weight import compute_sample_weight
# 目標函數改為 Macro AUC（呼應最終產品採機率輸出，而非強制分類的設計方向）
# 同時將 sample_weight 的加權強度也納入 Optuna 搜尋範圍，而非固定使用 balanced


def objective(trial):
    params = {
        'objective': 'multiclass',
        'boosting_type': 'gbdt',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.2, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 4, 31),
        'max_depth': trial.suggest_int('max_depth', 2, 8),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 50),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 0.0, 1.0),
        'reg_lambda': trial.suggest_float('reg_lambda', 0.0, 1.0),
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'random_state': 42,
        'n_jobs': -1,
        'verbose': -1,
    }

    # 加權強度：1.0 = 完全balanced（原始反比權重），0.0 = 完全不加權，讓 Optuna 自己找中間平衡點
    weight_power = trial.suggest_float('weight_power', 0.0, 1.5)

    tscv = TimeSeriesSplit(n_splits=5)
    scores = []

    for train_idx, val_idx in tscv.split(X_train):
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        base_weights = compute_sample_weight('balanced', y_tr)
        adjusted_weights = base_weights ** weight_power  # 開根號(0.5)~平方(2)之間的軟化/強化調整

        model = LGBMClassifier(**params)
        model.fit(X_tr, y_tr, sample_weight=adjusted_weights)

        y_pred_proba = model.predict_proba(X_val)
        classes = model.classes_
        y_val_binarized = label_binarize(y_val, classes=classes)

        # 避免驗證折裡剛好缺某個類別導致 roc_auc_score 出錯
        try:
            score = roc_auc_score(y_val_binarized, y_pred_proba, average='macro', multi_class='ovr')
        except ValueError:
            score = np.nan

        if not np.isnan(score):
            scores.append(score)

    return np.mean(scores) if scores else 0.0


# 執行optuna 
study = optuna.create_study(direction='maximize', study_name='model_b_auc_tuning')
study.optimize(objective, n_trials=100, show_progress_bar=True)

print('最佳參數:', study.best_params)
print('最佳 CV Macro AUC:', study.best_value)

# 用最佳參數，在完整訓練集上重新訓練，並在測試集上驗證 ----
best_params = study.best_params.copy()
weight_power = best_params.pop('weight_power')
best_params.update({
    'objective': 'multiclass',
    'boosting_type': 'gbdt',
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1,
})

final_weights = compute_sample_weight('balanced', y_train) ** weight_power

final_model = LGBMClassifier(**best_params)
final_model.fit(X_train, y_train, sample_weight=final_weights)

pred_train = final_model.predict(X_train)
pred_test = final_model.predict(X_test)

print('\n=== 調參後最終模型（以 AUC 為目標）===')
print('train:', classification_report(y_train, pred_train))
print('test:', classification_report(y_test, pred_test))

# 順便印出最終測試集的 AUC，方便跟之前的版本比較
pred_proba_test = final_model.predict_proba(X_test)
classes = final_model.classes_
y_test_binarized = label_binarize(y_test, classes=classes)

macro_auc = roc_auc_score(y_test_binarized, pred_proba_test, average='macro', multi_class='ovr')
print(f'\nTest Macro AUC: {macro_auc:.3f}')
for i, cls in enumerate(classes):
    auc = roc_auc_score(y_test_binarized[:, i], pred_proba_test[:, i])
    print(f'{cls} AUC: {auc:.3f}')

[I 2026-08-17 17:56:41,431] A new study created in memory with name: model_b_auc_tuning
Best trial: 0. Best value: 0.785224:   1%|          | 1/100 [00:01<03:12,  1.95s/it]

[I 2026-08-17 17:56:43,494] Trial 0 finished with value: 0.7852240883600584 and parameters: {'learning_rate': 0.055370993442038025, 'num_leaves': 20, 'max_depth': 2, 'min_child_samples': 15, 'subsample': 0.7102156970533747, 'colsample_bytree': 0.7889766683766379, 'reg_alpha': 0.8437067752951515, 'reg_lambda': 0.6825779101443652, 'n_estimators': 120, 'weight_power': 0.2818791112474444}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   2%|▏         | 2/100 [00:03<02:50,  1.74s/it]

[I 2026-08-17 17:56:45,096] Trial 1 finished with value: 0.7629010508044418 and parameters: {'learning_rate': 0.02799536418879848, 'num_leaves': 29, 'max_depth': 6, 'min_child_samples': 29, 'subsample': 0.5363527877079558, 'colsample_bytree': 0.6979261706344124, 'reg_alpha': 0.9649585124819329, 'reg_lambda': 0.3572055065722687, 'n_estimators': 234, 'weight_power': 0.6621256182409025}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   3%|▎         | 3/100 [00:04<02:17,  1.42s/it]

[I 2026-08-17 17:56:46,130] Trial 2 finished with value: 0.764699598501309 and parameters: {'learning_rate': 0.10136490356066175, 'num_leaves': 21, 'max_depth': 8, 'min_child_samples': 10, 'subsample': 0.8624685931721001, 'colsample_bytree': 0.7344669929263088, 'reg_alpha': 0.9418883805499817, 'reg_lambda': 0.17579586079657328, 'n_estimators': 101, 'weight_power': 0.6330427609873464}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   4%|▍         | 4/100 [00:05<01:57,  1.22s/it]

[I 2026-08-17 17:56:47,048] Trial 3 finished with value: 0.777945670244674 and parameters: {'learning_rate': 0.05054835712515288, 'num_leaves': 31, 'max_depth': 6, 'min_child_samples': 35, 'subsample': 0.6245520539326832, 'colsample_bytree': 0.879195362818199, 'reg_alpha': 0.36198461010932503, 'reg_lambda': 0.7509810899598481, 'n_estimators': 69, 'weight_power': 0.1791137199116019}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   5%|▌         | 5/100 [00:06<01:38,  1.04s/it]

[I 2026-08-17 17:56:47,767] Trial 4 finished with value: 0.7696017651031692 and parameters: {'learning_rate': 0.013160770914591953, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 32, 'subsample': 0.5901902829526557, 'colsample_bytree': 0.9381868645378714, 'reg_alpha': 0.14501498304060634, 'reg_lambda': 0.09303384977540563, 'n_estimators': 161, 'weight_power': 1.291219600612428}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   6%|▌         | 6/100 [00:07<01:35,  1.01s/it]

[I 2026-08-17 17:56:48,724] Trial 5 finished with value: 0.7587952641218096 and parameters: {'learning_rate': 0.04174080496672944, 'num_leaves': 26, 'max_depth': 6, 'min_child_samples': 25, 'subsample': 0.987989896123346, 'colsample_bytree': 0.6892607776540891, 'reg_alpha': 0.45926965794563124, 'reg_lambda': 0.322471523739975, 'n_estimators': 119, 'weight_power': 0.32789346274984266}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   7%|▋         | 7/100 [00:08<01:39,  1.08s/it]

[I 2026-08-17 17:56:49,927] Trial 6 finished with value: 0.7600896904938287 and parameters: {'learning_rate': 0.010816871361229224, 'num_leaves': 22, 'max_depth': 7, 'min_child_samples': 31, 'subsample': 0.5802833735687245, 'colsample_bytree': 0.5283428850098122, 'reg_alpha': 0.28019561373459423, 'reg_lambda': 0.5751917139755696, 'n_estimators': 174, 'weight_power': 0.9028435307842892}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   8%|▊         | 8/100 [00:09<01:51,  1.21s/it]

[I 2026-08-17 17:56:51,434] Trial 7 finished with value: 0.7493748194821761 and parameters: {'learning_rate': 0.05293213297385839, 'num_leaves': 21, 'max_depth': 6, 'min_child_samples': 21, 'subsample': 0.9429681131298959, 'colsample_bytree': 0.9886259317088567, 'reg_alpha': 0.10859158094160548, 'reg_lambda': 0.9636833476179332, 'n_estimators': 190, 'weight_power': 0.5072544135718215}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:   9%|▉         | 9/100 [00:11<01:51,  1.22s/it]

[I 2026-08-17 17:56:52,681] Trial 8 finished with value: 0.741362225435733 and parameters: {'learning_rate': 0.17817141666348998, 'num_leaves': 11, 'max_depth': 5, 'min_child_samples': 15, 'subsample': 0.8648288221443984, 'colsample_bytree': 0.6506242806018702, 'reg_alpha': 0.512531751262878, 'reg_lambda': 0.9192546234161567, 'n_estimators': 115, 'weight_power': 1.0577971192867013}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:  10%|█         | 10/100 [00:13<02:08,  1.42s/it]

[I 2026-08-17 17:56:54,559] Trial 9 finished with value: 0.7675403500510637 and parameters: {'learning_rate': 0.010104373421934912, 'num_leaves': 27, 'max_depth': 5, 'min_child_samples': 31, 'subsample': 0.5237449924255335, 'colsample_bytree': 0.9143390247847509, 'reg_alpha': 0.5360930593316906, 'reg_lambda': 0.8231721648115051, 'n_estimators': 262, 'weight_power': 0.8372018961797312}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 0. Best value: 0.785224:  11%|█         | 11/100 [00:14<02:05,  1.42s/it]

[I 2026-08-17 17:56:55,956] Trial 10 finished with value: 0.7769263519194496 and parameters: {'learning_rate': 0.021426977863881994, 'num_leaves': 4, 'max_depth': 2, 'min_child_samples': 49, 'subsample': 0.7167018538806758, 'colsample_bytree': 0.8051599859721141, 'reg_alpha': 0.7142291278727579, 'reg_lambda': 0.5646910081253919, 'n_estimators': 294, 'weight_power': 0.032530801596413084}. Best is trial 0 with value: 0.7852240883600584.


Best trial: 11. Best value: 0.790622:  12%|█▏        | 12/100 [00:14<01:38,  1.12s/it]

[I 2026-08-17 17:56:56,386] Trial 11 finished with value: 0.7906219578892301 and parameters: {'learning_rate': 0.07099336602069631, 'num_leaves': 16, 'max_depth': 3, 'min_child_samples': 43, 'subsample': 0.699763349946902, 'colsample_bytree': 0.8282586165430498, 'reg_alpha': 0.7616611949292895, 'reg_lambda': 0.6662505410738924, 'n_estimators': 52, 'weight_power': 0.07466561029842178}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  13%|█▎        | 13/100 [00:15<01:19,  1.10it/s]

[I 2026-08-17 17:56:56,823] Trial 12 finished with value: 0.7837786179588829 and parameters: {'learning_rate': 0.10794841413487268, 'num_leaves': 14, 'max_depth': 3, 'min_child_samples': 44, 'subsample': 0.714059916391841, 'colsample_bytree': 0.829184472749259, 'reg_alpha': 0.7416686432330384, 'reg_lambda': 0.6538948651209923, 'n_estimators': 50, 'weight_power': 0.2993882535956253}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  14%|█▍        | 14/100 [00:16<01:14,  1.15it/s]

[I 2026-08-17 17:56:57,600] Trial 13 finished with value: 0.7677783667952451 and parameters: {'learning_rate': 0.08010579548629362, 'num_leaves': 17, 'max_depth': 3, 'min_child_samples': 5, 'subsample': 0.7132912145789447, 'colsample_bytree': 0.7863899847517669, 'reg_alpha': 0.8009731459167188, 'reg_lambda': 0.43127450957546654, 'n_estimators': 85, 'weight_power': 0.12301806565572188}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  15%|█▌        | 15/100 [00:16<01:08,  1.23it/s]

[I 2026-08-17 17:56:58,277] Trial 14 finished with value: 0.7614584154761763 and parameters: {'learning_rate': 0.07870982742066589, 'num_leaves': 8, 'max_depth': 3, 'min_child_samples': 40, 'subsample': 0.8065047034696594, 'colsample_bytree': 0.5954371411129387, 'reg_alpha': 0.6522448372902685, 'reg_lambda': 0.7396388792657805, 'n_estimators': 144, 'weight_power': 0.42306267825602106}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  16%|█▌        | 16/100 [00:17<01:02,  1.35it/s]

[I 2026-08-17 17:56:58,857] Trial 15 finished with value: 0.7722680435150239 and parameters: {'learning_rate': 0.03032376724180896, 'num_leaves': 18, 'max_depth': 4, 'min_child_samples': 18, 'subsample': 0.6607316700392776, 'colsample_bytree': 0.7635048194567534, 'reg_alpha': 0.8593601860788427, 'reg_lambda': 0.5210151348533073, 'n_estimators': 64, 'weight_power': 0.0459494006814882}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  17%|█▋        | 17/100 [00:18<01:01,  1.36it/s]

[I 2026-08-17 17:56:59,584] Trial 16 finished with value: 0.7481088078649105 and parameters: {'learning_rate': 0.14647905788460736, 'num_leaves': 11, 'max_depth': 2, 'min_child_samples': 50, 'subsample': 0.7692812348929778, 'colsample_bytree': 0.8447570768303262, 'reg_alpha': 0.6101092805323394, 'reg_lambda': 0.8315396594104956, 'n_estimators': 204, 'weight_power': 0.2658581624385481}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  18%|█▊        | 18/100 [00:19<01:06,  1.23it/s]

[I 2026-08-17 17:57:00,564] Trial 17 finished with value: 0.7666970494000377 and parameters: {'learning_rate': 0.06935396539346952, 'num_leaves': 24, 'max_depth': 4, 'min_child_samples': 39, 'subsample': 0.7825116376252249, 'colsample_bytree': 0.8782883474399437, 'reg_alpha': 0.8579669463441224, 'reg_lambda': 0.6712871910815825, 'n_estimators': 140, 'weight_power': 0.5433231323771786}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  19%|█▉        | 19/100 [00:19<01:03,  1.28it/s]

[I 2026-08-17 17:57:01,285] Trial 18 finished with value: 0.7780024925422298 and parameters: {'learning_rate': 0.0350248074219358, 'num_leaves': 18, 'max_depth': 4, 'min_child_samples': 12, 'subsample': 0.6607538706103382, 'colsample_bytree': 0.6292480624596376, 'reg_alpha': 0.6500206965148683, 'reg_lambda': 0.414618274772497, 'n_estimators': 94, 'weight_power': 0.385932101869336}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  20%|██        | 20/100 [00:20<01:05,  1.22it/s]

[I 2026-08-17 17:57:02,184] Trial 19 finished with value: 0.7708239245469729 and parameters: {'learning_rate': 0.01775917657551264, 'num_leaves': 11, 'max_depth': 3, 'min_child_samples': 22, 'subsample': 0.867543251358514, 'colsample_bytree': 0.7357674234006462, 'reg_alpha': 0.9885103182678061, 'reg_lambda': 0.6493427677429622, 'n_estimators': 132, 'weight_power': 1.3998112030502923}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  21%|██        | 21/100 [00:21<01:10,  1.12it/s]

[I 2026-08-17 17:57:03,248] Trial 20 finished with value: 0.7874605644246869 and parameters: {'learning_rate': 0.061247143649769714, 'num_leaves': 14, 'max_depth': 2, 'min_child_samples': 7, 'subsample': 0.6524975207823703, 'colsample_bytree': 0.9709177951659943, 'reg_alpha': 0.8449612624847098, 'reg_lambda': 0.25442748333048065, 'n_estimators': 85, 'weight_power': 0.23341836254524678}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  22%|██▏       | 22/100 [00:22<01:00,  1.28it/s]

[I 2026-08-17 17:57:03,773] Trial 21 finished with value: 0.7899786036596824 and parameters: {'learning_rate': 0.06273022285132862, 'num_leaves': 14, 'max_depth': 2, 'min_child_samples': 7, 'subsample': 0.6662019069544803, 'colsample_bytree': 0.9709280678836694, 'reg_alpha': 0.8410660760863319, 'reg_lambda': 0.23367047773813354, 'n_estimators': 78, 'weight_power': 0.18570107744734415}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  23%|██▎       | 23/100 [00:22<00:53,  1.44it/s]

[I 2026-08-17 17:57:04,254] Trial 22 finished with value: 0.7616524205469372 and parameters: {'learning_rate': 0.11199275743646811, 'num_leaves': 15, 'max_depth': 2, 'min_child_samples': 7, 'subsample': 0.6634071422213774, 'colsample_bytree': 0.9962254785479895, 'reg_alpha': 0.7594621894925858, 'reg_lambda': 0.0005938702090403924, 'n_estimators': 77, 'weight_power': 0.17760551992585083}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 11. Best value: 0.790622:  24%|██▍       | 24/100 [00:23<00:47,  1.59it/s]

[I 2026-08-17 17:57:04,740] Trial 23 finished with value: 0.7690954745503752 and parameters: {'learning_rate': 0.07020723286400275, 'num_leaves': 7, 'max_depth': 3, 'min_child_samples': 10, 'subsample': 0.619629834249618, 'colsample_bytree': 0.9380899261631814, 'reg_alpha': 0.9025670027631902, 'reg_lambda': 0.24263764588343567, 'n_estimators': 61, 'weight_power': 0.04984863874433407}. Best is trial 11 with value: 0.7906219578892301.


Best trial: 24. Best value: 0.797453:  25%|██▌       | 25/100 [00:23<00:44,  1.69it/s]

[I 2026-08-17 17:57:05,239] Trial 24 finished with value: 0.7974533768476967 and parameters: {'learning_rate': 0.04098046087060057, 'num_leaves': 13, 'max_depth': 2, 'min_child_samples': 5, 'subsample': 0.5678436242918533, 'colsample_bytree': 0.954287369553273, 'reg_alpha': 0.6892792706117747, 'reg_lambda': 0.21759107008432615, 'n_estimators': 96, 'weight_power': 0.17780692556589195}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  26%|██▌       | 26/100 [00:24<00:40,  1.82it/s]

[I 2026-08-17 17:57:05,695] Trial 25 finished with value: 0.7867195859164546 and parameters: {'learning_rate': 0.040487207332702, 'num_leaves': 12, 'max_depth': 3, 'min_child_samples': 25, 'subsample': 0.5043902998959229, 'colsample_bytree': 0.8961054055695645, 'reg_alpha': 0.6955319695492695, 'reg_lambda': 0.1310865438614912, 'n_estimators': 51, 'weight_power': 0.0004479438315856399}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  27%|██▋       | 27/100 [00:25<00:48,  1.51it/s]

[I 2026-08-17 17:57:06,610] Trial 26 finished with value: 0.7938372484270394 and parameters: {'learning_rate': 0.024171186607347905, 'num_leaves': 9, 'max_depth': 4, 'min_child_samples': 14, 'subsample': 0.5695492458785738, 'colsample_bytree': 0.9411502717839721, 'reg_alpha': 0.5878680118382604, 'reg_lambda': 0.2234218021096308, 'n_estimators': 99, 'weight_power': 0.4442227558610458}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  28%|██▊       | 28/100 [00:25<00:50,  1.43it/s]

[I 2026-08-17 17:57:07,402] Trial 27 finished with value: 0.7829404978266026 and parameters: {'learning_rate': 0.02553200564843281, 'num_leaves': 7, 'max_depth': 4, 'min_child_samples': 15, 'subsample': 0.5622455320541261, 'colsample_bytree': 0.849981179130045, 'reg_alpha': 0.5463901110009696, 'reg_lambda': 0.012007000566309656, 'n_estimators': 102, 'weight_power': 0.4520429092932764}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  29%|██▉       | 29/100 [00:26<00:57,  1.24it/s]

[I 2026-08-17 17:57:08,449] Trial 28 finished with value: 0.7906108821897729 and parameters: {'learning_rate': 0.01795926461475203, 'num_leaves': 9, 'max_depth': 5, 'min_child_samples': 46, 'subsample': 0.6131638779275475, 'colsample_bytree': 0.9382627484321538, 'reg_alpha': 0.4078057330305026, 'reg_lambda': 0.3308494759083448, 'n_estimators': 159, 'weight_power': 0.6288138251857367}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  30%|███       | 30/100 [00:27<00:52,  1.33it/s]

[I 2026-08-17 17:57:09,081] Trial 29 finished with value: 0.7795952289183228 and parameters: {'learning_rate': 0.044931546189479234, 'num_leaves': 4, 'max_depth': 4, 'min_child_samples': 12, 'subsample': 0.5527858325261436, 'colsample_bytree': 0.9259787070140001, 'reg_alpha': 0.5791422964104672, 'reg_lambda': 0.4695358059778587, 'n_estimators': 106, 'weight_power': 0.7645499462180272}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  31%|███       | 31/100 [00:28<00:53,  1.30it/s]

[I 2026-08-17 17:57:09,902] Trial 30 finished with value: 0.7723784575166649 and parameters: {'learning_rate': 0.021809665782522265, 'num_leaves': 17, 'max_depth': 3, 'min_child_samples': 18, 'subsample': 0.5872823251457283, 'colsample_bytree': 0.8770890516482845, 'reg_alpha': 0.3220636646833492, 'reg_lambda': 0.10252422537935035, 'n_estimators': 128, 'weight_power': 0.35066561034718}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  32%|███▏      | 32/100 [00:29<01:01,  1.11it/s]

[I 2026-08-17 17:57:11,097] Trial 31 finished with value: 0.7905875731761656 and parameters: {'learning_rate': 0.015431113925045897, 'num_leaves': 8, 'max_depth': 5, 'min_child_samples': 45, 'subsample': 0.6122051902491606, 'colsample_bytree': 0.9562589358532313, 'reg_alpha': 0.4269672643082705, 'reg_lambda': 0.3425557201200796, 'n_estimators': 161, 'weight_power': 0.6157947416582155}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  33%|███▎      | 33/100 [00:30<01:07,  1.01s/it]

[I 2026-08-17 17:57:12,351] Trial 32 finished with value: 0.7599781179485419 and parameters: {'learning_rate': 0.03298715697652128, 'num_leaves': 9, 'max_depth': 5, 'min_child_samples': 45, 'subsample': 0.5353544620460889, 'colsample_bytree': 0.9049940433164989, 'reg_alpha': 0.22495729514652235, 'reg_lambda': 0.296449894941285, 'n_estimators': 226, 'weight_power': 0.7318136909406155}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  34%|███▍      | 34/100 [00:31<01:06,  1.01s/it]

[I 2026-08-17 17:57:13,360] Trial 33 finished with value: 0.7850729640529213 and parameters: {'learning_rate': 0.02365208160376771, 'num_leaves': 10, 'max_depth': 4, 'min_child_samples': 41, 'subsample': 0.7542511571976035, 'colsample_bytree': 0.9483143203595039, 'reg_alpha': 0.6414924197557906, 'reg_lambda': 0.1791674293743608, 'n_estimators': 155, 'weight_power': 0.5810060985079009}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  35%|███▌      | 35/100 [00:32<01:02,  1.05it/s]

[I 2026-08-17 17:57:14,197] Trial 34 finished with value: 0.7641833328228314 and parameters: {'learning_rate': 0.01873092726734124, 'num_leaves': 13, 'max_depth': 5, 'min_child_samples': 36, 'subsample': 0.6902835933420235, 'colsample_bytree': 0.8241724747140877, 'reg_alpha': 0.4046062428336269, 'reg_lambda': 0.1679828534062483, 'n_estimators': 113, 'weight_power': 0.9665031464562599}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  36%|███▌      | 36/100 [00:33<00:54,  1.18it/s]

[I 2026-08-17 17:57:14,804] Trial 35 finished with value: 0.7931355725219504 and parameters: {'learning_rate': 0.015920973914306, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 48, 'subsample': 0.6277152589988869, 'colsample_bytree': 0.8595677146204368, 'reg_alpha': 0.47903625536094896, 'reg_lambda': 0.05340139687471385, 'n_estimators': 93, 'weight_power': 0.47796352500861733}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  37%|███▋      | 37/100 [00:33<00:48,  1.30it/s]

[I 2026-08-17 17:57:15,381] Trial 36 finished with value: 0.793955835025052 and parameters: {'learning_rate': 0.014064417940145884, 'num_leaves': 6, 'max_depth': 7, 'min_child_samples': 35, 'subsample': 0.55659573151034, 'colsample_bytree': 0.8634615346773213, 'reg_alpha': 0.4600181464762985, 'reg_lambda': 0.0528932845029513, 'n_estimators': 87, 'weight_power': 0.48587699548022845}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  38%|███▊      | 38/100 [00:34<00:47,  1.29it/s]

[I 2026-08-17 17:57:16,160] Trial 37 finished with value: 0.7965599629237088 and parameters: {'learning_rate': 0.01293803715669304, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 37, 'subsample': 0.5666059524708019, 'colsample_bytree': 0.8673254281378309, 'reg_alpha': 0.47006319611148506, 'reg_lambda': 0.053571162296668993, 'n_estimators': 91, 'weight_power': 0.4655990622026978}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  39%|███▉      | 39/100 [00:35<00:46,  1.32it/s]

[I 2026-08-17 17:57:16,883] Trial 38 finished with value: 0.7808520926283514 and parameters: {'learning_rate': 0.012847392915774533, 'num_leaves': 5, 'max_depth': 7, 'min_child_samples': 35, 'subsample': 0.5010830326371387, 'colsample_bytree': 0.9015566534396515, 'reg_alpha': 0.3302429705778416, 'reg_lambda': 0.18749192705375917, 'n_estimators': 126, 'weight_power': 0.7338735239364789}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  40%|████      | 40/100 [00:36<00:45,  1.33it/s]

[I 2026-08-17 17:57:17,622] Trial 39 finished with value: 0.7873199779744663 and parameters: {'learning_rate': 0.012966770184220234, 'num_leaves': 5, 'max_depth': 8, 'min_child_samples': 27, 'subsample': 0.5746557174581128, 'colsample_bytree': 0.9735593465696499, 'reg_alpha': 0.2230759093564399, 'reg_lambda': 0.061595969425627055, 'n_estimators': 97, 'weight_power': 0.3851023038213524}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  41%|████      | 41/100 [00:36<00:42,  1.40it/s]

[I 2026-08-17 17:57:18,259] Trial 40 finished with value: 0.79048641866553 and parameters: {'learning_rate': 0.02649862995698271, 'num_leaves': 6, 'max_depth': 7, 'min_child_samples': 36, 'subsample': 0.5460160005352022, 'colsample_bytree': 0.7806665541787273, 'reg_alpha': 0.02829326463959969, 'reg_lambda': 0.125677153901593, 'n_estimators': 73, 'weight_power': 0.5206255450289058}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  42%|████▏     | 42/100 [00:37<00:40,  1.44it/s]

[I 2026-08-17 17:57:18,892] Trial 41 finished with value: 0.7940676560355422 and parameters: {'learning_rate': 0.01445380404946578, 'num_leaves': 6, 'max_depth': 8, 'min_child_samples': 48, 'subsample': 0.601318518122428, 'colsample_bytree': 0.8720910000428108, 'reg_alpha': 0.5037943198667149, 'reg_lambda': 0.059066990492715694, 'n_estimators': 91, 'weight_power': 0.4838788842292119}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  43%|████▎     | 43/100 [00:38<00:43,  1.30it/s]

[I 2026-08-17 17:57:19,833] Trial 42 finished with value: 0.7818183630729864 and parameters: {'learning_rate': 0.011438048948520851, 'num_leaves': 9, 'max_depth': 8, 'min_child_samples': 33, 'subsample': 0.5949001040372486, 'colsample_bytree': 0.8766552903239557, 'reg_alpha': 0.4726355604233797, 'reg_lambda': 0.05635998098080234, 'n_estimators': 112, 'weight_power': 0.6867865907032891}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 24. Best value: 0.797453:  44%|████▍     | 44/100 [00:38<00:41,  1.35it/s]

[I 2026-08-17 17:57:20,515] Trial 43 finished with value: 0.7884997417350471 and parameters: {'learning_rate': 0.014778889147246087, 'num_leaves': 7, 'max_depth': 7, 'min_child_samples': 29, 'subsample': 0.5213904738262112, 'colsample_bytree': 0.9126013931140434, 'reg_alpha': 0.5815532320141258, 'reg_lambda': 0.15134541905275561, 'n_estimators': 88, 'weight_power': 0.4274561089420842}. Best is trial 24 with value: 0.7974533768476967.


Best trial: 44. Best value: 0.817721:  45%|████▌     | 45/100 [00:39<00:36,  1.52it/s]

[I 2026-08-17 17:57:20,972] Trial 44 finished with value: 0.8177205031257984 and parameters: {'learning_rate': 0.01173378707067386, 'num_leaves': 5, 'max_depth': 8, 'min_child_samples': 38, 'subsample': 0.568026577680444, 'colsample_bytree': 0.8068389839354764, 'reg_alpha': 0.5151908804712073, 'reg_lambda': 0.21532635573965084, 'n_estimators': 66, 'weight_power': 0.309503999980361}. Best is trial 44 with value: 0.8177205031257984.


Best trial: 45. Best value: 0.819288:  46%|████▌     | 46/100 [00:39<00:31,  1.69it/s]

[I 2026-08-17 17:57:21,409] Trial 45 finished with value: 0.8192880438608586 and parameters: {'learning_rate': 0.011435468406580423, 'num_leaves': 4, 'max_depth': 7, 'min_child_samples': 38, 'subsample': 0.6349618962228102, 'colsample_bytree': 0.8078565730403955, 'reg_alpha': 0.5063506224816563, 'reg_lambda': 0.09035387421759651, 'n_estimators': 66, 'weight_power': 0.29060303702430423}. Best is trial 45 with value: 0.8192880438608586.


Best trial: 45. Best value: 0.819288:  47%|████▋     | 47/100 [00:40<00:28,  1.84it/s]

[I 2026-08-17 17:57:21,851] Trial 46 finished with value: 0.8182442349243549 and parameters: {'learning_rate': 0.010065804046530668, 'num_leaves': 4, 'max_depth': 8, 'min_child_samples': 42, 'subsample': 0.6344387418005881, 'colsample_bytree': 0.734884454601202, 'reg_alpha': 0.5100106734963675, 'reg_lambda': 0.2715076309331962, 'n_estimators': 65, 'weight_power': 0.3182052986588494}. Best is trial 45 with value: 0.8192880438608586.


Best trial: 47. Best value: 0.823156:  48%|████▊     | 48/100 [00:40<00:26,  1.98it/s]

[I 2026-08-17 17:57:22,263] Trial 47 finished with value: 0.8231558829579477 and parameters: {'learning_rate': 0.010018357352107701, 'num_leaves': 4, 'max_depth': 8, 'min_child_samples': 38, 'subsample': 0.6366657832773105, 'colsample_bytree': 0.7055940980492718, 'reg_alpha': 0.3829923645615564, 'reg_lambda': 0.2931961555181293, 'n_estimators': 63, 'weight_power': 0.2681603547710552}. Best is trial 47 with value: 0.8231558829579477.


Best trial: 47. Best value: 0.823156:  49%|████▉     | 49/100 [00:41<00:24,  2.06it/s]

[I 2026-08-17 17:57:22,692] Trial 48 finished with value: 0.8185255087242922 and parameters: {'learning_rate': 0.010323501532709108, 'num_leaves': 4, 'max_depth': 7, 'min_child_samples': 41, 'subsample': 0.6331259985839998, 'colsample_bytree': 0.7158139193580758, 'reg_alpha': 0.39144712133006426, 'reg_lambda': 0.39689072525411395, 'n_estimators': 63, 'weight_power': 0.304383662709249}. Best is trial 47 with value: 0.8231558829579477.


Best trial: 49. Best value: 0.824539:  50%|█████     | 50/100 [00:41<00:23,  2.12it/s]

[I 2026-08-17 17:57:23,133] Trial 49 finished with value: 0.8245388595535083 and parameters: {'learning_rate': 0.010064728575988969, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 38, 'subsample': 0.6459455301191607, 'colsample_bytree': 0.6834313822451178, 'reg_alpha': 0.3549677504898402, 'reg_lambda': 0.2740839920994449, 'n_estimators': 64, 'weight_power': 0.3013525939572423}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  51%|█████     | 51/100 [00:42<00:25,  1.91it/s]

[I 2026-08-17 17:57:23,784] Trial 50 finished with value: 0.8202084431284119 and parameters: {'learning_rate': 0.010399909496075239, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 41, 'subsample': 0.6410707136503753, 'colsample_bytree': 0.6951255897489041, 'reg_alpha': 0.364601642208784, 'reg_lambda': 0.38956427620446465, 'n_estimators': 60, 'weight_power': 0.23045470705891674}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  52%|█████▏    | 52/100 [00:42<00:23,  2.01it/s]

[I 2026-08-17 17:57:24,217] Trial 51 finished with value: 0.8195787716131446 and parameters: {'learning_rate': 0.010122606207410678, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 42, 'subsample': 0.6849013099848257, 'colsample_bytree': 0.6921538907080894, 'reg_alpha': 0.368692588723722, 'reg_lambda': 0.3875023490299234, 'n_estimators': 56, 'weight_power': 0.24096351066778424}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  53%|█████▎    | 53/100 [00:43<00:22,  2.13it/s]

[I 2026-08-17 17:57:24,626] Trial 52 finished with value: 0.8228882329633598 and parameters: {'learning_rate': 0.01128652233396536, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.7396271829328468, 'colsample_bytree': 0.6831230505484003, 'reg_alpha': 0.35988839338048384, 'reg_lambda': 0.3823266412049637, 'n_estimators': 59, 'weight_power': 0.2418148666383486}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  54%|█████▍    | 54/100 [00:43<00:20,  2.23it/s]

[I 2026-08-17 17:57:25,024] Trial 53 finished with value: 0.8235202639932737 and parameters: {'learning_rate': 0.011216364045912799, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 39, 'subsample': 0.7242724739908311, 'colsample_bytree': 0.6731800529005195, 'reg_alpha': 0.27204203867571186, 'reg_lambda': 0.3866317584893002, 'n_estimators': 54, 'weight_power': 0.25769208707054725}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  55%|█████▌    | 55/100 [00:43<00:19,  2.29it/s]

[I 2026-08-17 17:57:25,436] Trial 54 finished with value: 0.8140667412315308 and parameters: {'learning_rate': 0.011720418482181257, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.7359626256140321, 'colsample_bytree': 0.6727270342640244, 'reg_alpha': 0.27143441534589474, 'reg_lambda': 0.38031711624345743, 'n_estimators': 50, 'weight_power': 0.11725102287486727}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  56%|█████▌    | 56/100 [00:44<00:19,  2.27it/s]

[I 2026-08-17 17:57:25,887] Trial 55 finished with value: 0.8206034716470676 and parameters: {'learning_rate': 0.010182051449779624, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.6878660320148974, 'colsample_bytree': 0.6324410367791998, 'reg_alpha': 0.3535355510199703, 'reg_lambda': 0.4713849399658744, 'n_estimators': 77, 'weight_power': 0.23590678014183925}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  57%|█████▋    | 57/100 [00:44<00:20,  2.12it/s]

[I 2026-08-17 17:57:26,427] Trial 56 finished with value: 0.7892583980876857 and parameters: {'learning_rate': 0.01628446540243291, 'num_leaves': 8, 'max_depth': 6, 'min_child_samples': 33, 'subsample': 0.732516432172563, 'colsample_bytree': 0.612688360828979, 'reg_alpha': 0.1886354987954536, 'reg_lambda': 0.4889634733136601, 'n_estimators': 76, 'weight_power': 0.10361243629183109}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  58%|█████▊    | 58/100 [00:46<00:28,  1.50it/s]

[I 2026-08-17 17:57:27,553] Trial 57 finished with value: 0.8078130674813044 and parameters: {'learning_rate': 0.012191849163510753, 'num_leaves': 30, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.7933948294832979, 'colsample_bytree': 0.5570407891017382, 'reg_alpha': 0.27230423537117654, 'reg_lambda': 0.44622434637621217, 'n_estimators': 79, 'weight_power': 0.22898448723090598}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  59%|█████▉    | 59/100 [00:46<00:31,  1.32it/s]

[I 2026-08-17 17:57:28,525] Trial 58 finished with value: 0.8072767992503757 and parameters: {'learning_rate': 0.01094665235335458, 'num_leaves': 7, 'max_depth': 6, 'min_child_samples': 39, 'subsample': 0.6813221561718534, 'colsample_bytree': 0.6691545167582884, 'reg_alpha': 0.3221770209068063, 'reg_lambda': 0.5622598049958971, 'n_estimators': 57, 'weight_power': 0.15997877348504802}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  60%|██████    | 60/100 [00:47<00:27,  1.47it/s]

[I 2026-08-17 17:57:29,020] Trial 59 finished with value: 0.7932468330492487 and parameters: {'learning_rate': 0.013865281975383394, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 31, 'subsample': 0.8264162321079291, 'colsample_bytree': 0.6418719218365583, 'reg_alpha': 0.13073355001405218, 'reg_lambda': 0.289533797929205, 'n_estimators': 72, 'weight_power': 0.3736963233464011}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  61%|██████    | 61/100 [00:48<00:31,  1.23it/s]

[I 2026-08-17 17:57:30,140] Trial 60 finished with value: 0.7812844987761086 and parameters: {'learning_rate': 0.01652160839689534, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 33, 'subsample': 0.7317638706866072, 'colsample_bytree': 0.7121787716903673, 'reg_alpha': 0.30121005270284856, 'reg_lambda': 0.5249601382231246, 'n_estimators': 298, 'weight_power': 0.20832517178441914}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  62%|██████▏   | 62/100 [00:49<00:26,  1.44it/s]

[I 2026-08-17 17:57:30,552] Trial 61 finished with value: 0.8213644529185059 and parameters: {'learning_rate': 0.010430485736283203, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.6885999547958582, 'colsample_bytree': 0.6827924187866279, 'reg_alpha': 0.3648415589313204, 'reg_lambda': 0.3630639171580569, 'n_estimators': 55, 'weight_power': 0.24409654105750803}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  63%|██████▎   | 63/100 [00:49<00:22,  1.64it/s]

[I 2026-08-17 17:57:30,972] Trial 62 finished with value: 0.8129455921243005 and parameters: {'learning_rate': 0.011151473335970944, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 44, 'subsample': 0.7075806988453571, 'colsample_bytree': 0.6700487595188716, 'reg_alpha': 0.34862183234013033, 'reg_lambda': 0.3559252427909543, 'n_estimators': 58, 'weight_power': 0.2693250736768955}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  64%|██████▍   | 64/100 [00:49<00:21,  1.69it/s]

[I 2026-08-17 17:57:31,529] Trial 63 finished with value: 0.7956390790352679 and parameters: {'learning_rate': 0.01269187751378823, 'num_leaves': 7, 'max_depth': 5, 'min_child_samples': 39, 'subsample': 0.6477124630916655, 'colsample_bytree': 0.7516384895732496, 'reg_alpha': 0.23713110327050504, 'reg_lambda': 0.3151724001616322, 'n_estimators': 80, 'weight_power': 0.14671046305334323}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  65%|██████▌   | 65/100 [00:50<00:19,  1.77it/s]

[I 2026-08-17 17:57:32,025] Trial 64 finished with value: 0.8024418519106904 and parameters: {'learning_rate': 0.010102869176768822, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 47, 'subsample': 0.7552181633517835, 'colsample_bytree': 0.708151113331973, 'reg_alpha': 0.3590787272026622, 'reg_lambda': 0.4426610616325225, 'n_estimators': 72, 'weight_power': 0.08524483731316196}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  66%|██████▌   | 66/100 [00:50<00:17,  1.93it/s]

[I 2026-08-17 17:57:32,432] Trial 65 finished with value: 0.8080246806157214 and parameters: {'learning_rate': 0.0198176037825156, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 41, 'subsample': 0.6757208624020802, 'colsample_bytree': 0.5837884580856084, 'reg_alpha': 0.4319286255737266, 'reg_lambda': 0.6081738612380536, 'n_estimators': 58, 'weight_power': 0.35490396168857863}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  67%|██████▋   | 67/100 [00:51<00:18,  1.79it/s]

[I 2026-08-17 17:57:33,086] Trial 66 finished with value: 0.7809457403812341 and parameters: {'learning_rate': 0.013493778482179202, 'num_leaves': 5, 'max_depth': 7, 'min_child_samples': 37, 'subsample': 0.6932299382470491, 'colsample_bytree': 0.6223834365442107, 'reg_alpha': 0.3732606528566663, 'reg_lambda': 0.4993598754334991, 'n_estimators': 70, 'weight_power': 1.1540526963077529}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  68%|██████▊   | 68/100 [00:52<00:17,  1.80it/s]

[I 2026-08-17 17:57:33,637] Trial 67 finished with value: 0.8043287101041022 and parameters: {'learning_rate': 0.011009998468140676, 'num_leaves': 8, 'max_depth': 5, 'min_child_samples': 44, 'subsample': 0.7238383245849566, 'colsample_bytree': 0.6589752942106312, 'reg_alpha': 0.2557684103032556, 'reg_lambda': 0.3694041234563743, 'n_estimators': 82, 'weight_power': 0.2559019418756828}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  69%|██████▉   | 69/100 [00:52<00:16,  1.89it/s]

[I 2026-08-17 17:57:34,101] Trial 68 finished with value: 0.8098624370366249 and parameters: {'learning_rate': 0.0122227712032286, 'num_leaves': 7, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.7528894621639284, 'colsample_bytree': 0.6427589867274492, 'reg_alpha': 0.18649002013431723, 'reg_lambda': 0.40929263221320705, 'n_estimators': 51, 'weight_power': 0.19997316243817714}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  70%|███████   | 70/100 [00:53<00:15,  1.89it/s]

[I 2026-08-17 17:57:34,630] Trial 69 finished with value: 0.808822120566664 and parameters: {'learning_rate': 0.015038126898124468, 'num_leaves': 4, 'max_depth': 7, 'min_child_samples': 42, 'subsample': 0.704482095416891, 'colsample_bytree': 0.6991401171191418, 'reg_alpha': 0.30243533388754656, 'reg_lambda': 0.4650743470593479, 'n_estimators': 106, 'weight_power': 0.0058762682649019515}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  71%|███████   | 71/100 [00:53<00:15,  1.91it/s]

[I 2026-08-17 17:57:35,139] Trial 70 finished with value: 0.807715512350728 and parameters: {'learning_rate': 0.010834382318173168, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 34, 'subsample': 0.653459757848201, 'colsample_bytree': 0.6781926073934772, 'reg_alpha': 0.3022400742883649, 'reg_lambda': 0.3224762578484147, 'n_estimators': 60, 'weight_power': 0.407325975783832}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  72%|███████▏  | 72/100 [00:53<00:13,  2.07it/s]

[I 2026-08-17 17:57:35,535] Trial 71 finished with value: 0.820078579957588 and parameters: {'learning_rate': 0.010021231834755137, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.685104747764784, 'colsample_bytree': 0.6865962821485326, 'reg_alpha': 0.3804452188752703, 'reg_lambda': 0.3808655010962186, 'n_estimators': 56, 'weight_power': 0.24669273853255588}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  73%|███████▎  | 73/100 [00:54<00:13,  2.05it/s]

[I 2026-08-17 17:57:36,030] Trial 72 finished with value: 0.8114531736469515 and parameters: {'learning_rate': 0.010035025434312193, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 38, 'subsample': 0.6689610956831553, 'colsample_bytree': 0.7266935010517918, 'reg_alpha': 0.43335387443329054, 'reg_lambda': 0.4226525804644336, 'n_estimators': 68, 'weight_power': 0.14155104405870847}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  74%|███████▍  | 74/100 [00:55<00:13,  1.98it/s]

[I 2026-08-17 17:57:36,570] Trial 73 finished with value: 0.8207327451496218 and parameters: {'learning_rate': 0.011835399151709433, 'num_leaves': 4, 'max_depth': 5, 'min_child_samples': 46, 'subsample': 0.64409187881136, 'colsample_bytree': 0.6885970155548858, 'reg_alpha': 0.3424927996120355, 'reg_lambda': 0.3574484001078884, 'n_estimators': 50, 'weight_power': 0.33778643615172277}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  75%|███████▌  | 75/100 [00:55<00:12,  1.97it/s]

[I 2026-08-17 17:57:37,085] Trial 74 finished with value: 0.8048635728648851 and parameters: {'learning_rate': 0.012401257830068292, 'num_leaves': 5, 'max_depth': 5, 'min_child_samples': 46, 'subsample': 0.6437909262834779, 'colsample_bytree': 0.7581581770252716, 'reg_alpha': 0.34209145514336015, 'reg_lambda': 0.29140893978058935, 'n_estimators': 82, 'weight_power': 0.3499083766880581}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  76%|███████▌  | 76/100 [00:55<00:11,  2.10it/s]

[I 2026-08-17 17:57:37,490] Trial 75 finished with value: 0.8068747255787032 and parameters: {'learning_rate': 0.013712531121972266, 'num_leaves': 6, 'max_depth': 5, 'min_child_samples': 45, 'subsample': 0.9785386029021321, 'colsample_bytree': 0.6580439715327484, 'reg_alpha': 0.4111827509993694, 'reg_lambda': 0.34283967806168053, 'n_estimators': 50, 'weight_power': 0.19649684191068023}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  77%|███████▋  | 77/100 [00:56<00:11,  2.06it/s]

[I 2026-08-17 17:57:37,992] Trial 76 finished with value: 0.7852952392942046 and parameters: {'learning_rate': 0.017387406582393617, 'num_leaves': 8, 'max_depth': 5, 'min_child_samples': 49, 'subsample': 0.6121980501510843, 'colsample_bytree': 0.604950594581908, 'reg_alpha': 0.1777351559626408, 'reg_lambda': 0.5268644857665096, 'n_estimators': 74, 'weight_power': 0.06100497110253067}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  78%|███████▊  | 78/100 [00:57<00:13,  1.59it/s]

[I 2026-08-17 17:57:38,955] Trial 77 finished with value: 0.7946864543144188 and parameters: {'learning_rate': 0.011817490572938329, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.7189066486874739, 'colsample_bytree': 0.6465253340749618, 'reg_alpha': 0.4411120109968072, 'reg_lambda': 0.24926076922412316, 'n_estimators': 261, 'weight_power': 0.3287826788300062}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  79%|███████▉  | 79/100 [00:57<00:12,  1.71it/s]

[I 2026-08-17 17:57:39,434] Trial 78 finished with value: 0.8051363684288162 and parameters: {'learning_rate': 0.01099881787022284, 'num_leaves': 6, 'max_depth': 7, 'min_child_samples': 37, 'subsample': 0.6977598278355953, 'colsample_bytree': 0.7449909585744126, 'reg_alpha': 0.30095625419485256, 'reg_lambda': 0.26859346678722373, 'n_estimators': 62, 'weight_power': 0.4066189621403907}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  80%|████████  | 80/100 [00:58<00:11,  1.78it/s]

[I 2026-08-17 17:57:39,942] Trial 79 finished with value: 0.7395416721079476 and parameters: {'learning_rate': 0.013424040102697474, 'num_leaves': 27, 'max_depth': 5, 'min_child_samples': 47, 'subsample': 0.7684984628237596, 'colsample_bytree': 0.6319865139716627, 'reg_alpha': 0.25217574786832375, 'reg_lambda': 0.35758052584625366, 'n_estimators': 67, 'weight_power': 1.4880086381133077}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  81%|████████  | 81/100 [00:59<00:10,  1.74it/s]

[I 2026-08-17 17:57:40,550] Trial 80 finished with value: 0.8073704021736793 and parameters: {'learning_rate': 0.01462212010059306, 'num_leaves': 7, 'max_depth': 5, 'min_child_samples': 35, 'subsample': 0.6607169727339642, 'colsample_bytree': 0.7245245584433301, 'reg_alpha': 0.39517610164354966, 'reg_lambda': 0.31564166283944833, 'n_estimators': 55, 'weight_power': 0.2745066687430496}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  82%|████████▏ | 82/100 [00:59<00:09,  1.82it/s]

[I 2026-08-17 17:57:41,038] Trial 81 finished with value: 0.8173021481875427 and parameters: {'learning_rate': 0.010814132652841023, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 42, 'subsample': 0.6791332330070838, 'colsample_bytree': 0.6841534130136185, 'reg_alpha': 0.37806710058660714, 'reg_lambda': 0.41362997660518575, 'n_estimators': 60, 'weight_power': 0.23279855385592893}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  83%|████████▎ | 83/100 [00:59<00:08,  1.98it/s]

[I 2026-08-17 17:57:41,442] Trial 82 finished with value: 0.8207272944014707 and parameters: {'learning_rate': 0.012174014413391658, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.6474261752509867, 'colsample_bytree': 0.6978704986925404, 'reg_alpha': 0.3430453553200222, 'reg_lambda': 0.46542742731483927, 'n_estimators': 50, 'weight_power': 0.28310046710324493}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  84%|████████▍ | 84/100 [01:00<00:07,  2.04it/s]

[I 2026-08-17 17:57:41,896] Trial 83 finished with value: 0.8132817398420086 and parameters: {'learning_rate': 0.012131564614690529, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 39, 'subsample': 0.6026816233964835, 'colsample_bytree': 0.6998995613016044, 'reg_alpha': 0.3596461133747671, 'reg_lambda': 0.46432964073287664, 'n_estimators': 71, 'weight_power': 0.17629572398641413}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  85%|████████▌ | 85/100 [01:00<00:07,  2.13it/s]

[I 2026-08-17 17:57:42,323] Trial 84 finished with value: 0.8144556410306144 and parameters: {'learning_rate': 0.01292444144546671, 'num_leaves': 5, 'max_depth': 7, 'min_child_samples': 43, 'subsample': 0.6435359771494225, 'colsample_bytree': 0.6598643771377342, 'reg_alpha': 0.2844243062002102, 'reg_lambda': 0.4926119967934711, 'n_estimators': 50, 'weight_power': 0.33427092761609284}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  86%|████████▌ | 86/100 [01:01<00:06,  2.05it/s]

[I 2026-08-17 17:57:42,851] Trial 85 finished with value: 0.7935406300004306 and parameters: {'learning_rate': 0.015499185650727065, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 50, 'subsample': 0.6265776858118938, 'colsample_bytree': 0.7021535991214369, 'reg_alpha': 0.3307187563953872, 'reg_lambda': 0.547476140497558, 'n_estimators': 84, 'weight_power': 0.29166465098778416}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  87%|████████▋ | 87/100 [01:01<00:06,  2.11it/s]

[I 2026-08-17 17:57:43,293] Trial 86 finished with value: 0.8187977970306051 and parameters: {'learning_rate': 0.010902146891231156, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 41, 'subsample': 0.6635993763533119, 'colsample_bytree': 0.7204547705159048, 'reg_alpha': 0.33862082360081414, 'reg_lambda': 0.4322253221416103, 'n_estimators': 64, 'weight_power': 0.21687562895667895}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  88%|████████▊ | 88/100 [01:02<00:06,  1.81it/s]

[I 2026-08-17 17:57:44,034] Trial 87 finished with value: 0.7428164557973604 and parameters: {'learning_rate': 0.18518247251919812, 'num_leaves': 7, 'max_depth': 7, 'min_child_samples': 44, 'subsample': 0.7058194063855411, 'colsample_bytree': 0.5859623182982592, 'reg_alpha': 0.21247900671877054, 'reg_lambda': 0.3347008864606414, 'n_estimators': 77, 'weight_power': 0.39007342647243987}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  89%|████████▉ | 89/100 [01:02<00:05,  1.92it/s]

[I 2026-08-17 17:57:44,481] Trial 88 finished with value: 0.8089592777827015 and parameters: {'learning_rate': 0.013922850206251424, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 36, 'subsample': 0.6163379418714728, 'colsample_bytree': 0.7724781364876442, 'reg_alpha': 0.44790507627750265, 'reg_lambda': 0.375632957459469, 'n_estimators': 62, 'weight_power': 0.12420939919492938}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  90%|█████████ | 90/100 [01:03<00:05,  1.81it/s]

[I 2026-08-17 17:57:45,103] Trial 89 finished with value: 0.8022337476133178 and parameters: {'learning_rate': 0.01208931748793566, 'num_leaves': 23, 'max_depth': 5, 'min_child_samples': 38, 'subsample': 0.7419371196441819, 'colsample_bytree': 0.6906151519780703, 'reg_alpha': 0.4095421460008014, 'reg_lambda': 0.20150064524426176, 'n_estimators': 88, 'weight_power': 0.2854828499964334}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  91%|█████████ | 91/100 [01:04<00:04,  1.86it/s]

[I 2026-08-17 17:57:45,608] Trial 90 finished with value: 0.8073382491852529 and parameters: {'learning_rate': 0.011629278583123053, 'num_leaves': 10, 'max_depth': 6, 'min_child_samples': 46, 'subsample': 0.6522121957837177, 'colsample_bytree': 0.7399189163017051, 'reg_alpha': 0.3158180605655992, 'reg_lambda': 0.6007383849780898, 'n_estimators': 56, 'weight_power': 0.16594737582889496}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  92%|█████████▏| 92/100 [01:04<00:03,  2.01it/s]

[I 2026-08-17 17:57:46,007] Trial 91 finished with value: 0.8197828941572449 and parameters: {'learning_rate': 0.010507367136528918, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.6755597536319218, 'colsample_bytree': 0.6846832051838893, 'reg_alpha': 0.3806941696833571, 'reg_lambda': 0.3943915038468258, 'n_estimators': 55, 'weight_power': 0.24273943867615685}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  93%|█████████▎| 93/100 [01:04<00:03,  2.08it/s]

[I 2026-08-17 17:57:46,448] Trial 92 finished with value: 0.8175681829489602 and parameters: {'learning_rate': 0.010166614076145608, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 41, 'subsample': 0.6873491649132033, 'colsample_bytree': 0.6652805795623732, 'reg_alpha': 0.3523498168089783, 'reg_lambda': 0.3036907125522086, 'n_estimators': 69, 'weight_power': 0.25850898969492914}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  94%|█████████▍| 94/100 [01:05<00:03,  1.86it/s]

[I 2026-08-17 17:57:47,119] Trial 93 finished with value: 0.8102351203598008 and parameters: {'learning_rate': 0.011416031246215477, 'num_leaves': 6, 'max_depth': 6, 'min_child_samples': 43, 'subsample': 0.6408625220868631, 'colsample_bytree': 0.6817538430086353, 'reg_alpha': 0.27854805200443566, 'reg_lambda': 0.35692388249389034, 'n_estimators': 56, 'weight_power': 0.362662199705109}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  95%|█████████▌| 95/100 [01:06<00:02,  1.88it/s]

[I 2026-08-17 17:57:47,637] Trial 94 finished with value: 0.8122211590451529 and parameters: {'learning_rate': 0.012759364312725091, 'num_leaves': 5, 'max_depth': 6, 'min_child_samples': 40, 'subsample': 0.7216222500423471, 'colsample_bytree': 0.6521198848715098, 'reg_alpha': 0.41980460310152895, 'reg_lambda': 0.44755803815024403, 'n_estimators': 76, 'weight_power': 0.20732678513736777}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  96%|█████████▌| 96/100 [01:06<00:01,  2.00it/s]

[I 2026-08-17 17:57:48,064] Trial 95 finished with value: 0.8134016898619374 and parameters: {'learning_rate': 0.010037882301611432, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 45, 'subsample': 0.6915537280416632, 'colsample_bytree': 0.7086369125218427, 'reg_alpha': 0.38608260734322036, 'reg_lambda': 0.27067872758955097, 'n_estimators': 65, 'weight_power': 0.30668036734823223}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  97%|█████████▋| 97/100 [01:06<00:01,  2.10it/s]

[I 2026-08-17 17:57:48,486] Trial 96 finished with value: 0.8145721605399447 and parameters: {'learning_rate': 0.010770146306797124, 'num_leaves': 5, 'max_depth': 7, 'min_child_samples': 37, 'subsample': 0.6573254618996985, 'colsample_bytree': 0.6932058955759647, 'reg_alpha': 0.3580970584024284, 'reg_lambda': 0.39891784490865206, 'n_estimators': 54, 'weight_power': 0.429933936778586}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  98%|█████████▊| 98/100 [01:07<00:00,  2.19it/s]

[I 2026-08-17 17:57:48,895] Trial 97 finished with value: 0.8184775725368088 and parameters: {'learning_rate': 0.011596305870478336, 'num_leaves': 4, 'max_depth': 4, 'min_child_samples': 39, 'subsample': 0.6695953975558417, 'colsample_bytree': 0.6270549915293886, 'reg_alpha': 0.48536140790654664, 'reg_lambda': 0.37650531037123225, 'n_estimators': 60, 'weight_power': 0.3277602573442092}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539:  99%|█████████▉| 99/100 [01:07<00:00,  2.24it/s]

[I 2026-08-17 17:57:49,317] Trial 98 finished with value: 0.8052531095593614 and parameters: {'learning_rate': 0.013364123461500657, 'num_leaves': 6, 'max_depth': 5, 'min_child_samples': 42, 'subsample': 0.58244612910212, 'colsample_bytree': 0.6767500923357667, 'reg_alpha': 0.2521795063518097, 'reg_lambda': 0.4719656245802416, 'n_estimators': 50, 'weight_power': 0.1002247836821954}. Best is trial 49 with value: 0.8245388595535083.


Best trial: 49. Best value: 0.824539: 100%|██████████| 100/100 [01:08<00:00,  1.46it/s]


[I 2026-08-17 17:57:49,820] Trial 99 finished with value: 0.7981799047486698 and parameters: {'learning_rate': 0.012520692628926548, 'num_leaves': 8, 'max_depth': 6, 'min_child_samples': 48, 'subsample': 0.6271468672905476, 'colsample_bytree': 0.6367296005677622, 'reg_alpha': 0.31936105586744856, 'reg_lambda': 0.41949423463489705, 'n_estimators': 70, 'weight_power': 0.5548797389445341}. Best is trial 49 with value: 0.8245388595535083.
最佳參數: {'learning_rate': 0.010064728575988969, 'num_leaves': 4, 'max_depth': 6, 'min_child_samples': 38, 'subsample': 0.6459455301191607, 'colsample_bytree': 0.6834313822451178, 'reg_alpha': 0.3549677504898402, 'reg_lambda': 0.2740839920994449, 'n_estimators': 64, 'weight_power': 0.3013525939572423}
最佳 CV Macro AUC: 0.8245388595535083

=== 調參後最終模型（以 AUC 為目標）===
train:                precision    recall  f1-score   support

  Cooperation       0.85      0.98      0.91       777
High_Conflict       0.85      0.56      0.68        95
 Low_Conflict       0.83 

In [30]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score, precision_score, f1_score

# 使用 Optuna 調完的 final_model，取得測試集的機率預測
y_pred_proba = final_model.predict_proba(X_test)
classes = list(final_model.classes_)

# 針對 High_Conflict 掃描不同門檻
hc_idx = classes.index('High_Conflict')
y_test_hc_binary = (y_test == 'High_Conflict').astype(int)

hc_results = []
for threshold in np.arange(0.10, 0.55, 0.025):
    y_pred_hc = (y_pred_proba[:, hc_idx] >= threshold).astype(int)
    recall = recall_score(y_test_hc_binary, y_pred_hc, zero_division=0)
    precision = precision_score(y_test_hc_binary, y_pred_hc, zero_division=0)
    f1 = f1_score(y_test_hc_binary, y_pred_hc, zero_division=0)
    hc_results.append({'threshold': threshold, 'recall': recall, 'precision': precision, 'f1': f1})

hc_df = pd.DataFrame(hc_results)
print('=== High_Conflict 門檻掃描 ===')
print(hc_df.to_string(index=False))

# 針對 Low_Conflict 掃描不同門檻
lc_idx = classes.index('Low_Conflict')
y_test_lc_binary = (y_test == 'Low_Conflict').astype(int)

lc_results = []
for threshold in np.arange(0.10, 0.55, 0.025):
    y_pred_lc = (y_pred_proba[:, lc_idx] >= threshold).astype(int)
    recall = recall_score(y_test_lc_binary, y_pred_lc, zero_division=0)
    precision = precision_score(y_test_lc_binary, y_pred_lc, zero_division=0)
    f1 = f1_score(y_test_lc_binary, y_pred_lc, zero_division=0)
    lc_results.append({'threshold': threshold, 'recall': recall, 'precision': precision, 'f1': f1})

lc_df = pd.DataFrame(lc_results)
print('\n=== Low_Conflict 門檻掃描 ===')
print(lc_df.to_string(index=False))
best_hc_threshold = hc_df.loc[hc_df['f1'].idxmax()]
best_lc_threshold = lc_df.loc[lc_df['f1'].idxmax()]

print(f'\n建議 High_Conflict 門檻: {best_hc_threshold["threshold"]:.3f} '
      f'(recall={best_hc_threshold["recall"]:.3f}, precision={best_hc_threshold["precision"]:.3f}, f1={best_hc_threshold["f1"]:.3f})')
print(f'建議 Low_Conflict 門檻: {best_lc_threshold["threshold"]:.3f} '
      f'(recall={best_lc_threshold["recall"]:.3f}, precision={best_lc_threshold["precision"]:.3f}, f1={best_lc_threshold["f1"]:.3f})')

=== High_Conflict 門檻掃描 ===
 threshold   recall  precision       f1
     0.100 0.977273   0.273885 0.427861
     0.125 0.886364   0.410526 0.561151
     0.150 0.840909   0.513889 0.637931
     0.175 0.795455   0.538462 0.642202
     0.200 0.750000   0.550000 0.634615
     0.225 0.704545   0.620000 0.659574
     0.250 0.636364   0.622222 0.629213
     0.275 0.568182   0.625000 0.595238
     0.300 0.522727   0.605263 0.560976
     0.325 0.500000   0.666667 0.571429
     0.350 0.500000   0.687500 0.578947
     0.375 0.386364   0.680000 0.492754
     0.400 0.363636   0.666667 0.470588
     0.425 0.204545   0.692308 0.315789
     0.450 0.022727   0.500000 0.043478
     0.475 0.000000   0.000000 0.000000
     0.500 0.000000   0.000000 0.000000
     0.525 0.000000   0.000000 0.000000

=== Low_Conflict 門檻掃描 ===
 threshold   recall  precision       f1
     0.100 1.000000   0.272727 0.428571
     0.125 1.000000   0.272727 0.428571
     0.150 0.925926   0.480769 0.632911
     0.175 0.888889   0.51

### Threshold Tuning 結果

- Optuna改用AUC當目標，weight_power也交給它搜尋 → 找到0.30（接近不加權）
- Test Macro AUC 0.918，比之前手動調參略高
- 但predict()預設0.5門檻下 recall很低（HC 0.36, LC 0.35），因為機率普遍壓低
- 掃描門檻後找到較佳點：
  - HC門檻0.225：recall 0.705, precision 0.620, f1 0.660
  - LC門檻0.275：recall 0.713, precision 0.726, f1 0.720
- 跟之前手動調參版本打平略優，定案採用這組

In [5]:
# retrain
import json
import joblib
from lightgbm import LGBMClassifier
from sklearn.utils.class_weight import compute_sample_weight

best_params = {
    'learning_rate': 0.018909621443467715,
    'num_leaves': 13,
    'max_depth': 2,
    'min_child_samples': 6,
    'subsample': 0.6992340850376021,
    'colsample_bytree': 0.8203261117853924,
    'reg_alpha': 0.4480047925625076,
    'reg_lambda': 0.39004263179543947,
    'n_estimators': 66,
    'objective': 'multiclass',
    'boosting_type': 'gbdt',
    'random_state': 42,
    'n_jobs': -1,
    'verbose': -1
}
with open('../outputs/para/lgb_01.json', 'w') as f:
    json.dump(best_params, f, indent=2)

weight_power = 0.3013525939572423

final_weights = compute_sample_weight('balanced', y) ** weight_power
 
final_model = LGBMClassifier(**best_params)
final_model.fit(X, y, sample_weight=final_weights)

 
joblib.dump(final_model, '../outputs/models/mod_lgb.pkl')

    

['../outputs/models/mod_lgb.pkl']

In [ ]:
import json

model_config = {
    'features': X_train.columns.tolist(),
    'thresholds': {
        'High_Conflict': 0.225,
        'Low_Conflict': 0.275
    }
}

with open('../outputs/models/model_config.json', 'w') as f:
    json.dump(model_config, f, indent=2)

: 